# -*- coding: utf-8 -*-
"""Catalogue Top 10 Geek — ÉCRANS PC (relevé du 09/10/2026).
50 écrans, 10 par usage. Chaque écran est vendu sur Amazon.fr au moment du relevé et couvert par au moins un test presse.
Notes : (média, note sur 10 ou None si le test n'est pas noté, url). Conversion : 4/5 -> 8/10, 87 % -> 8,7/10.
scope « gamme » : une partie des tests porte sur une variante proche (autre suffixe, autre taille de la même série).
Champs : cat, short, ref, badge, verdict, strengths, weak, m (taille/définition, fréquence), notes, scope,
asin, amz (libellé marchand), price (constaté le 09/10/2026), pour, eviter."""

TOP = "Le choix de la bande"


def E(cat, short, ref, badge, verdict, strengths, weak, m, notes, asin, amz, price, pour, eviter, scope="modele", seller="Amazon"):
    return dict(cat=cat, short=short, ref=ref, badge=badge, verdict=verdict, strengths=strengths, weak=weak, m=m,
                notes=notes, scope=scope, asin=asin, amz=amz, price=price, pour=pour, eviter=eviter, seller=seller)


RT = "RTINGS"
MN = "MonitorNerds"
ECR = {}

# =====================================================================================================================
#                                                   BUREAUTIQUE
# =====================================================================================================================
ECR["dell-s2725dc"] = E("e-bureau", "Dell 27 Plus S2725DC", "27\" QHD · IPS · 144 Hz · USB-C", TOP,
    "Un 27 pouces QHD fluide à 144 Hz, bien réglable et doté d'un USB-C qui alimente le portable : l'écran de bureau le plus simple à recommander.",
    ["Définition QHD nette sur 27\"", "USB-C avec alimentation du portable", "Pied réglable, ports USB en plus"],
    ["Pas pensé pour la retouche photo exigeante", "Les utilisateurs avancés auront besoin d'un dock"],
    ("27\" QHD", "144 Hz"),
    [("TechRadar", 10, "https://www.techradar.com/pro/dell-27-plus-qhd-usb-c-s2725dc-business-monitor-review"),
     (RT, None, "https://www.rtings.com/monitor/reviews/dell/s2725dc")],
    "B0FQ5B9BB1", "Dell 27 Plus USB-C Écran PC - S2725DC, QHD (2560x1440), 144Hz, IPS", 232.48,
    "Vous cherchez un écran 27\" polyvalent pour le travail, avec un seul câble USB-C pour brancher et recharger votre portable.",
    "Vous retouchez des photos de façon professionnelle ou voulez une image 4K.")
ECR["dell-s2725qs"] = E("e-bureau", "Dell 27 Plus S2725QS", "27\" 4K UHD · IPS · 120 Hz", "La 4K accessible",
    "La 4K sur 27 pouces à prix contenu, avec de belles couleurs et un mode 120 Hz : un excellent écran de travail, au contraste un peu faible.",
    ["Image 4K très nette", "Couleurs fidèles", "120 Hz pour une navigation fluide"],
    ["Contraste faible (noirs grisâtres)", "Fonctions limitées, pas d'USB-C vidéo"],
    ("27\" 4K", "120 Hz"),
    [("Wired", None, "https://www.wired.com/review/dell-27-plus-4k-monitor-s2725qs/"),
     (MN, None, "https://monitornerds.com/dell-s2725qs-review/?utm_source=rss&utm_medium=rss&utm_campaign=dell-s2725qs-review"),
     (RT, None, "https://www.rtings.com/monitor/reviews/dell/s2725qs")],
    "B0F29RH4RY", "Dell 27 Plus Écran PC - S2725QS, 4K UHD (3840x2160), 120Hz, IPS, 4ms", 274.75,
    "Vous voulez une image 4K très fine pour lire et travailler toute la journée, sans payer un écran pro.",
    "Vous regardez beaucoup de films dans le noir (contraste faible) ou voulez un seul câble USB-C.")
ECR["dell-s2725qc"] = E("e-bureau", "Dell 27 Plus S2725QC", "27\" 4K UHD · IPS · 120 Hz · USB-C 65 W", "Le 4K à un seul câble",
    "La version USB-C du S2725QS : 4K, 120 Hz, pied réglable dans tous les sens et charge 65 W pour le portable. Le contraste reste celui d'un IPS classique.",
    ["4K et 120 Hz", "USB-C avec charge 65 W", "Pied réglable dans tous les sens, haut-parleurs"],
    ["Design tout plastique", "HDR limité, contraste en retrait"],
    ("27\" 4K", "120 Hz"),
    [("Les Numériques", 8, "https://www.lesnumeriques.com/moniteur/dell-s2725qc-p78273/test.html"),
     (RT, None, "https://www.rtings.com/monitor/reviews/dell/s2725qc")],
    "B0F29RSLHP", "Dell 27 Plus USB-C Écran PC - S2725QC, 4K UHD (3840x2160), 120Hz, IPS, 4ms", 291.69,
    "Vous branchez un portable au bureau et voulez la 4K, la recharge et l'image par un seul câble USB-C.",
    "Vous attendez un vrai rendu HDR ou une finition haut de gamme.")
ECR["dell-s3225qs"] = E("e-bureau", "Dell 32 Plus S3225QS", "32\" 4K UHD · VA · 120 Hz", "Le grand écran 4K",
    "Un 32 pouces 4K à dalle VA, bien contrasté et fluide à 120 Hz, pour afficher plusieurs fenêtres côte à côte à prix raisonnable.",
    ["Grande surface 32\" en 4K", "Dalle VA bien contrastée", "120 Hz"],
    ["Angles de vision moins larges qu'un IPS", "Testé sans note chiffrée"],
    ("32\" 4K", "120 Hz"),
    [(RT, None, "https://www.rtings.com/monitor/reviews/dell/s3225qs")],
    "B0F29SKXFQ", "Dell 32 Plus Écran PC - S3225QS, 4K UHD (3840x2160), 120Hz, VA, 4ms", 328.87,
    "Vous voulez un grand écran 4K pour travailler sur plusieurs documents à la fois et regarder des vidéos.",
    "Vous regardez l'écran de biais ou à plusieurs : la dalle VA perd en couleurs sur les côtés.")
ECR["dell-u2724de"] = E("e-bureau", "Dell UltraSharp U2724DE", "27\" QHD · IPS Black · 120 Hz · Thunderbolt 4", "Le poste pro complet",
    "La station de travail de bureau : dalle IPS Black contrastée, 120 Hz, Thunderbolt 4 avec charge 90 W, KVM et réseau. Cher, mais tout est intégré.",
    ["Contraste IPS Black supérieur aux IPS classiques", "Thunderbolt 4 (charge 90 W), KVM, Ethernet", "Couleurs calibrées d'usine"],
    ["Prix élevé pour du QHD", "Pas de HDR ni de haut-parleurs"],
    ("27\" QHD", "120 Hz"),
    [("IT Pro", 10, "https://www.itpro.com/hardware/monitors/dell-ultrasharp-u2724de-review-a-great-all-rounder"),
     ("DisplayNinja", 8, "https://www.displayninja.com/dell-u2724de-review/"),
     ("PCWorld", None, "https://www.pcworld.com/article/2164596/dell-u2724de-review.html"),
     (MN, None, "https://monitornerds.com/dell-u2724de-review/?utm_source=rss&utm_medium=rss&utm_campaign=dell-u2724de-review"),
     ("Tweakers", None, "https://tweakers.net/reviews/12964/dell-ultrasharp-u2724de-fijne-maar-dure-thuiswerkmonitor.html")],
    "B0CNJSX8N8", "Dell UltraSharp 27 Écran PC - U2724DE, QHD (2560x1440), 120Hz, IPS Black", 360.75,
    "Vous montez un poste de travail fixe pour un portable et voulez tout centraliser : charge, clavier, souris, réseau, sur un seul câble.",
    "Vous cherchez la 4K ou un budget serré : la connectique Thunderbolt se paie.")
ECR["benq-gw2790ce"] = E("e-bureau", "BenQ GW2790CE", "27\" Full HD · IPS · 144 Hz · USB-C", "Le moins cher en 27\"",
    "Un 27 pouces Full HD soigné pour les yeux (anti-scintillement, lumière bleue réduite), fluide à 144 Hz et doté de l'USB-C, pour moins de 100 €.",
    ["Prix très bas", "Technologies de confort visuel", "USB-C sur cette version CE"],
    ["Full HD un peu juste sur 27\" (texte moins fin)", "Pied seulement inclinable"],
    ("27\" Full HD", "144 Hz"),
    [("Gadget Bridge", 6, "https://www.gadgetbridge.com/gadget-reviews/benq-gw2790tc-monitor-review-surprisingly-smooth-ride/"),
     ("GizTele", None, "https://www.giztele.com/benq-gw2790-monitor/"),
     (MN, None, "https://monitornerds.com/benq-gw2790-review/?utm_source=rss&utm_medium=rss&utm_campaign=benq-gw2790-review")],
    "B0FQTCCJP1", "BenQ GW2790CE Moniteur IPS 27\" FHD 1080p 144Hz Eye-Care, télétravail, USB-C", 95.82,
    "Vous voulez un grand écran confortable pour le télétravail ou les devoirs, au prix le plus bas.",
    "Vous lisez beaucoup de petit texte : en Full HD sur 27\", une définition QHD sera plus nette.", scope="gamme")
ECR["benq-gw2490ce"] = E("e-bureau", "BenQ GW2490CE", "24\" Full HD · IPS · 144 Hz · USB-C", "Le petit format malin",
    "Le 24 pouces de bureau par excellence : image très propre pour le prix, menus simples, confort visuel et USB-C sur cette version.",
    ["Excellent rapport qualité-prix", "Taille idéale pour un petit bureau", "Confort visuel, USB-C"],
    ["Pied basique", "Haut-parleurs anecdotiques"],
    ("24\" Full HD", "144 Hz"),
    [("IT Pro", 10, "https://www.itpro.com/hardware/monitors/benq-gw2490-monitor-review-a-brilliant-office-monitor-for-under-gbp100"),
     ("GizTele", None, "https://www.giztele.com/benq-gw2490-monitor/")],
    "B0FQSS4P5D", "BenQ GW2490CE Moniteur IPS 23,8\" FHD 1080p 144Hz Eye-Care, télétravail, USB-C", 102.69,
    "Vous avez peu de place et voulez un second écran fiable et reposant pour le travail.",
    "Vous voulez régler la hauteur de l'écran : le pied ne fait que s'incliner.", scope="gamme")
ECR["lg-32un88a"] = E("e-bureau", "LG UltraFine Ergo 32UN88A", "32\" 4K UHD · IPS · bras Ergo · USB-C", "Le plus ergonomique",
    "Un 32 pouces 4K monté sur un bras articulé qui se fixe au bureau : on place l'écran exactement où l'on veut, et la colorimétrie est très bonne.",
    ["Bras articulé qui libère le bureau", "Belle image 4K, couleurs justes", "USB-C"],
    ["Pas assez lumineux pour un vrai HDR", "60 Hz seulement"],
    ("32\" 4K", "60 Hz"),
    [("TechRadar", None, "https://www.techradar.com/reviews/lg-32un880-ultrafine-display-ergo"),
     ("Korben", None, "https://korben.info/en/lg-ultra-fine-display-ergo-32un880-review.html"),
     ("PurePC", None, "https://www.purepc.pl/lg-ultrafine-display-ergo-32un880-test-biurowego-monitora-z-matryca-ips-4k-hdr-oraz-z-ergonomiczna-podstawa-typu-ergo")],
    "B088BMZ41V", "LG Ergo Ultrafine 32UN88AP-W Ecran PC 4K 32\" - Dalle IPS 3840x2160, 60Hz, HDR 10", 461.53,
    "Vous voulez un grand écran 4K que l'on rapproche, tourne ou repousse d'un geste, sans pied qui encombre le bureau.",
    "Vous jouez : l'écran est limité à 60 Hz.", scope="gamme")
ECR["lg-32up83a"] = E("e-bureau", "LG UltraFine 32UP83A", "32\" 4K UHD · IPS · USB-C", "Le 32\" 4K polyvalent",
    "Un 32 pouces 4K IPS aux couleurs étendues, avec USB-C et pied réglable : un grand écran de travail confortable, aussi à l'aise en photo amateur.",
    ["4K IPS sur 32\"", "Large gamme de couleurs", "USB-C, pied réglable"],
    ["60 Hz seulement", "Testé sans note chiffrée"],
    ("32\" 4K", "60 Hz"),
    [(MN, None, "https://monitornerds.com/lg-32up83a-w-review/"),
     ("PC Monitors", None, "https://pcmonitors.info/lg/lg-32up83a-4k-uhd-ips-with-usb-c/")],
    "B0DQXKKBDF", "LG 32UP83AK-W 32-inch Ultrafine 4K UHD (3840 x 2160) IPS Computer Monitor, 60Hz, HDR10", 483.65,
    "Vous voulez un grand écran 4K aux couleurs justes pour le travail et la retouche occasionnelle.",
    "Vous cherchez de la fluidité pour jouer (60 Hz).", seller="Amazon")
ECR["asus-pa279cv"] = E("e-bureau", "Asus ProArt PA279CV", "27\" 4K UHD · IPS · USB-C 65 W", "La 4K calibrée",
    "Un 27 pouces 4K calibré d'usine (sRGB), avec USB-C 65 W et un pied très réglable : précis et abordable, mais limité à 60 Hz et peu lumineux en mode fidèle.",
    ["Couleurs sRGB fidèles (calibration usine)", "USB-C 65 W", "Pied très réglable"],
    ["60 Hz et léger flou de mouvement", "Pas assez lumineux ni étendu pour le HDR"],
    ("27\" 4K", "60 Hz"),
    [("Trusted Reviews", None, "https://www.trustedreviews.com/reviews/asus-proart-pa279cv"),
     ("Digital Camera World", None, "https://www.digitalcameraworld.com/reviews/asus-proart-display-pa279cv-review"),
     (MN, None, "https://monitornerds.com/asus-proart-pa279cv-review")],
    "B08JH7KQKV", "ASUS ProArt PA279CV 27 Pouces 4K Écran Professionnel USB-C", 288.43,
    "Vous voulez un écran 4K aux couleurs justes pour la bureautique, le web et la photo amateur.",
    "Vous jouez ou retouchez en Adobe RGB : la gamme de couleurs se limite au sRGB.")

# =====================================================================================================================
#                                                   GAMING
# =====================================================================================================================
ECR["aoc-q27g4zd"] = E("e-gaming", "AOC Agon Q27G4ZD", "27\" QHD · QD-OLED · 280 Hz", TOP,
    "L'OLED gaming devenu abordable : contraste infini, couleurs justes sans réglage, 280 Hz et un pied réglable, pour le prix d'un bon écran IPS.",
    ["Noirs et contraste OLED", "280 Hz, réactivité immédiate", "Prix très bien placé"],
    ["Luminosité HDR limitée", "Pas d'USB-C ni de haut-parleurs"],
    ("27\" QHD", "280 Hz"),
    [("Tom's Hardware", 8, "https://www.tomshardware.com/monitors/gaming-monitors/aoc-q27g4zd-qd-oled-240-hz-gaming-monitor-review"),
     ("MYC Media", 9, "https://myc-media.de/aoc-q27g4zdr-265%e2%80%b3-qd-oled-gaming-monitor-im-test/"),
     ("LeCafeDuGeek", 8, "https://lecafedugeek.fr/test-aoc-q27g4zdr-un-ecran-gaming-qui-rend-loled-enfin-accessible/"),
     ("Multiplayer.it", 7, "https://multiplayer.it/recensioni/aoc-agon-q27g4zdr-recensione-monitor-qd-oled-240-hz.html"),
     ("Wired", None, "https://www.wired.com/review/aoc-q27g4zd-review/")],
    "B0G6XZVL36", "AOC Gaming Moniteur Q27G4ZD 27 Pouce 280Hz QD-OLED Dalle, 0.03ms GtG, HDR400 TrueBlack", 357.99,
    "Vous voulez passer à l'OLED pour jouer en QHD sans dépasser un budget raisonnable.",
    "Vous jouez dans une pièce très lumineuse ou voulez brancher un portable en USB-C.", scope="gamme")
ECR["alienware-aw2725d"] = E("e-gaming", "Alienware AW2725D", "27\" QHD · QD-OLED · 280 Hz", "Le QD-OLED premium",
    "Un QD-OLED 280 Hz très bien fini, lumineux en HDR et très fluide, avec un pied solide : un excellent écran de jeu QHD.",
    ["Couleurs et contraste QD-OLED", "280 Hz, G-Sync et FreeSync", "Construction et pied de qualité"],
    ["Pas d'USB-C", "Ni haut-parleurs ni prise casque"],
    ("27\" QHD", "280 Hz"),
    [("PCWorld", 8, "https://www.pcworld.com/article/2848200/alienware-aw2725d-review.html"),
     ("Tom's Hardware", 8, "https://www.tomshardware.com/monitors/gaming-monitors/alienware-aw2725d-27-inch-qd-oled-qhd-280-hz-gaming-monitor-review"),
     ("Expert Reviews", 8, "https://www.expertreviews.co.uk/technology/monitors/alienware-aw2725d-review"),
     ("Connect.de", None, "https://www.connect.de/testbericht/dell-alienware-aw2725d-test-3211420.html")],
    "B0FHB4KWBF", "Alienware 27 Écran PC Gaming - AW2725D, QHD (2560x1440), 280Hz, QD OLED", 379.33,
    "Vous voulez un OLED QHD très rapide et bien construit pour les jeux compétitifs comme les jeux solo.",
    "Vous comptez y brancher un portable en USB-C ou utiliser le son de l'écran.")
ECR["alienware-aw2726dm"] = E("e-gaming", "Alienware AW2726DM", "27\" QHD · QD-OLED · 240 Hz", "L'OLED le plus abordable",
    "Le QD-OLED d'Alienware à prix serré : 240 Hz, excellent contraste, traitement antireflet et micro intégré. La connectique reste minimale.",
    ["Contraste et couleurs QD-OLED", "Prix contenu pour un OLED", "Antireflet efficace"],
    ["Connectique limitée", "Calibrage d'usine à peaufiner"],
    ("27\" QHD", "240 Hz"),
    [("MKAU Gaming", 9, "https://www.mkaugaming.com/all-review-list/alienware-27-240hz-qd-oled-aw2726dm-gaming-monitor-hardware-review/"),
     ("PC Gamer", 8.5, "https://www.pcgamer.com/hardware/gaming-monitors/alienware-aw2726dm-review/"),
     ("GamesRadar", 8, "https://www.gamesradar.com/hardware/tvs-monitors/alienware-aw2726dm-review/"),
     (RT, None, "https://www.rtings.com/monitor/reviews/dell/alienware-aw2726dm"),
     ("Wired", None, "https://www.wired.com/review/alienware-27-qd-oled-aw2726dm/")],
    "B0GYG3VLMR", "Alienware 27 Écran PC Gaming - AW2726DM, QHD (2560x1440), 240Hz, QD OLED", 351.58,
    "Vous voulez un premier écran OLED pour jouer en QHD, au meilleur prix.",
    "Vous avez besoin de beaucoup de ports ou d'USB-C.")
ECR["alienware-aw2725q"] = E("e-gaming", "Alienware AW2725Q", "27\" 4K UHD · QD-OLED · 240 Hz", "La 4K OLED sur 27\"",
    "La 4K à 240 Hz sur 27 pouces en QD-OLED : une image d'une finesse et d'un contraste remarquables, adorée par la presse, avec une garantie marquage de 3 ans.",
    ["4K très fine (166 ppp) en OLED", "240 Hz, réactivité exemplaire", "Garantie de 3 ans couvrant le marquage"],
    ["Noirs moins profonds en pièce lumineuse", "Peu de ports, pas d'USB-C vidéo"],
    ("27\" 4K", "240 Hz"),
    [("MKAU Gaming", 9, "https://www.mkaugaming.com/all-review-list/alienware-27-4k-qd-oled-aw2725q-gaming-monitor-hardware-review/"),
     ("Windows Central", 9, "https://www.windowscentral.com/accessories/monitors/alienware-27-4k-qd-oled-gaming-monitor-aw2725q-review"),
     ("TechAeris", 9, "https://techaeris.com/2025/04/02/alienware-aw2725q-review/?utm_source=rss&utm_medium=rss&utm_campaign=alienware-aw2725q-review"),
     (RT, 9, "https://www.rtings.com/monitor/reviews/dell/alienware-aw2725q"),
     ("Frandroid", 9, "https://www.frandroid.com/marques/alienware/2520007_test-du-alienware-aw2725q-lecran-4k-27-pouces-ideal"),
     ("Engadget", 9, "https://www.engadget.com/gaming/pc/alienware-aw2725q-review-an-exceptional-oled-gaming-display-120046049.html?src=rss"),
     ("GamesRadar", 8, "https://www.gamesradar.com/hardware/tvs-monitors/alienware-aw2725q-review/"),
     ("Laptop Mag", 8, "https://www.laptopmag.com/gaming/gaming-monitors/alienware-27-4k-qd-oled-aw2725q-gaming-monitor-review"),
     ("DisplayNinja", 8, "https://www.displayninja.com/dell-alienware-aw2725q-review/"),
     ("Tom's Hardware", 8, "https://www.tomshardware.com/monitors/gaming-monitors/alienware-aw2725q-4k-240-hz-oled-gaming-monitor-review-serious-value-and-high-performance"),
     ("Trusted Reviews", None, "https://www.trustedreviews.com/reviews/alienware-aw2725q"),
     ("PCWorld", None, "https://www.pcworld.com/article/2640120/alienware-aw2725q-monitor-review.html")],
    "B0F2JJ1T9K", "Alienware 27 Écran PC Gaming - AW2725Q, 4K UHD (3840x2160), 240Hz, QD OLED", 519.08,
    "Vous avez une carte graphique puissante et voulez la meilleure image possible sur un 27 pouces, en jeu comme au travail.",
    "Votre PC ne peut pas tenir la 4K en jeu : un QHD OLED sera plus fluide et moins cher.")
ECR["asus-pg32ucdm"] = E("e-gaming", "Asus ROG Swift PG32UCDM", "32\" 4K UHD · QD-OLED · 240 Hz", "Le grand 4K OLED",
    "Le 32 pouces 4K OLED de référence : image exceptionnelle, 240 Hz, connectique complète avec USB-C 90 W. Cher et gourmand, mais la presse est unanime.",
    ["Qualité d'image OLED exceptionnelle", "4K à 240 Hz sur 32\"", "Connectique complète, USB-C 90 W"],
    ["Prix élevé", "Pic lumineux HDR limité, pas de haut-parleurs"],
    ("32\" 4K", "240 Hz"),
    [("T3", 10, "https://www.t3.com/reviews/asus-rog-swift-oled-pg32ucdm-review"),
     ("Les Numériques", 10, "https://www.lesnumeriques.com/moniteur/asus-rog-swift-oled-pg32ucdm-p74611/test.html"),
     ("GizTele", 9, "https://www.giztele.com/asus-rog-swift-oled-pg32ucdm-monitor/"),
     (RT, 9, "https://www.rtings.com/monitor/reviews/asus/rog-swift-oled-pg32ucdm"),
     ("Frandroid", 9, "https://www.frandroid.com/marques/asus/1984436_test-de-lasus-rog-swift-oled-pg32ucdm"),
     ("Multiplayer.it", 9, "https://multiplayer.it/recensioni/asus-rog-swift-oled-pg32ucdm-recensione-monitor-4k-240hz.html"),
     ("DisplayNinja", 8, "https://www.displayninja.com/asus-pg32ucdm-review/"),
     ("Geeknetic", 8, "https://www.geeknetic.es/Review/2815/ASUS-ROG-Swift-OLED-PG32UCDM-Review.html"),
     ("PCWorld", None, "https://www.pcworld.com/article/2256541/asus-rog-swift-oled-pg32ucdm-review.html"),
     ("Eurogamer", None, "https://www.eurogamer.net/digitalfoundry-2024-asus-rog-swift-oled-pg32ucdm-review-the-best-gaming-monitor-we-have-tested?utm_source=feed&utm_medium=rss&utm_campaign=feed")],
    "B0F94H18X8", "ASUS ROG Swift PG32UCDMZ 32 Pouces 4K 240Hz Écran PC Gamer OLED QD-OLED", 777.62,
    "Vous voulez le grand écran OLED 4K le plus abouti pour jouer et travailler, et le budget suit.",
    "Votre bureau est peu profond (32\") ou votre carte graphique ne tient pas la 4K.", scope="gamme")
ECR["sony-inzone-m10s"] = E("e-gaming", "Sony Inzone M10S", "27\" QHD · OLED · 480 Hz", "Le plus rapide",
    "Un OLED QHD à 480 Hz pensé pour l'e-sport : clarté de mouvement inouïe et latence très faible. Pour joueurs compétitifs exigeants, à un prix élevé.",
    ["480 Hz, clarté de mouvement exceptionnelle", "Latence très faible", "Pied compact bien conçu"],
    ["Très cher pour du QHD", "Pas d'USB-C, garantie marquage d'un an"],
    ("27\" QHD", "480 Hz"),
    [("TechRadar", 10, "https://www.techradar.com/gaming/sony-inzone-m10s-review"),
     (RT, 9, "https://www.rtings.com/monitor/reviews/sony/inzone-m10s"),
     ("Frandroid", 8, "https://www.frandroid.com/marques/sony/2441836_test-du-sony-inzone-m10s"),
     ("GamesRadar", 8, "https://www.gamesradar.com/hardware/tvs-monitors/sony-inzone-m10s-review/"),
     ("T3", 8, "https://www.t3.com/tech/monitors/sony-inzone-m10s-review"),
     ("Multiplayer.it", 7, "https://multiplayer.it/recensioni/sony-inzone-m10s-recensione-monitor-oled-gaming.html"),
     ("Digital Trends", None, "https://www.digitaltrends.com/computing/sony-inzone-m10s-review/"),
     ("PCWorld", None, "https://www.pcworld.com/article/2521339/sony-inzone-m10s-review.html")],
    "B0DGV5LPKS", "Sony INZONE M10S 27\" OLED QHD PC Gaming Monitor: 1440p, 480Hz, 0.03ms GTG", 832.49,
    "Vous jouez en compétitif (FPS, e-sport) et chaque milliseconde compte.",
    "Vous jouez surtout à des jeux solo : un OLED 240 Hz offre la même image pour bien moins cher.")
ECR["msi-mpg-321urx"] = E("e-gaming", "MSI MPG 321URX", "32\" 4K UHD · QD-OLED · 240 Hz", "Le 32\" OLED malin",
    "Un 32 pouces 4K QD-OLED à 240 Hz, très bien noté, avec peu de scintillement VRR et une garantie marquage de 3 ans, souvent moins cher que ses rivaux.",
    ["Image QD-OLED 4K éclatante", "240 Hz, VRR peu sujet au scintillement", "Garantie de 3 ans contre le marquage"],
    ["Noirs légèrement violacés en pièce éclairée", "Pas de câble USB-C ni DisplayPort fourni"],
    ("32\" 4K", "240 Hz"),
    [("KitGuru", 9, "https://www.kitguru.net/peripherals/dominic-moass/msi-mpg-321urx-review-4k-240hz-qd-oled/"),
     (RT, 9, "https://www.rtings.com/monitor/reviews/msi/mpg-321urx-qd-oled"),
     ("DisplayNinja", 8, "https://www.displayninja.com/msi-mpg-321urx-review/"),
     ("Geeknetic", 8, "https://www.geeknetic.es/Review/2785/MSI-MPG-321URX-QD-OLED-Review.html"),
     ("Multiplayer.it", 8, "https://multiplayer.it/recensioni/msi-mpg-321urx-recensione-monitor-qd-oled-gaming.html"),
     ("Club386", None, "https://www.club386.com/msi-mpg-321urx-qd-oled-review-a-pixel-performance-prodigy/"),
     ("PCWorld", None, "https://www.pcworld.com/article/2615229/msi-mpg-321urxw-qd-oled-review.html"),
     ("HardwareCooking", None, "https://www.hardwarecooking.fr/test-msi-mpg-321urxw-qd-oled/")],
    "B0BSN2BXC5", "MSI MPG 321URXW QD-OLED Écran Gaming 31.5\" UHD", 619.01,
    "Vous voulez un grand OLED 4K pour jouer et regarder des films, au meilleur rapport prix/qualité.",
    "Vous jouez dans une pièce très éclairée, où les noirs perdent de leur profondeur.", scope="gamme")
ECR["msi-mpg-271qr-x50"] = E("e-gaming", "MSI MPG 271QR X50", "26,5\" QHD · QD-OLED · 500 Hz", "Le 500 Hz",
    "Un QD-OLED de dernière génération à 500 Hz : fluidité inégalée et très bonne luminosité plein écran. Un écran d'exception, au tarif qui va avec.",
    ["500 Hz, fluidité exceptionnelle", "Dalle QD-OLED de 4e génération", "Bonne luminosité plein écran"],
    ["Très cher", "Point blanc à recalibrer en SDR"],
    ("26,5\" QHD", "500 Hz"),
    [("PC Gamer", 8.9, "https://www.pcgamer.com/hardware/gaming-monitors/msi-mpg-271qr-x50-qd-oled-gaming-monitor-review/"),
     ("Multiplayer.it", 8, "https://multiplayer.it/recensioni/msi-mpg-271qr-x50-recensione-monitor-qd-oled-27.html"),
     ("Wccftech", None, "https://wccftech.com/review/msi-mpg-271qr-x50-qd-oled-gaming-monitor-review-500hz-80-gbps-support-with-built-in-npu-powered-oled-care-3-0/")],
    "B097PLXF1K", "MSI MPG 271QR QD-OLED X50 Écran Gaming 26.5\" WQHD", 535.82,
    "Vous jouez en compétitif et voulez l'OLED le plus fluide du moment.",
    "Votre PC ne dépasse pas 200 images par seconde dans vos jeux : les 500 Hz ne serviront pas.")
ECR["aoc-ag276qsg2"] = E("e-gaming", "AOC Agon Pro AG276QSG2", "27\" QHD · Fast IPS · 360 Hz · G-Sync Pulsar", "L'IPS e-sport",
    "Un IPS QHD à 360 Hz doté du G-Sync Pulsar : une netteté de mouvement de premier ordre pour les jeux de tir. L'image reste celle d'un IPS face aux OLED.",
    ["360 Hz et G-Sync Pulsar", "Netteté de mouvement remarquable", "Pied très réglable, bon logiciel"],
    ["Cher pour un IPS", "Noirs nuageux, fuites de lumière en bord d'écran"],
    ("27\" QHD", "360 Hz"),
    [("KitGuru", 8, "https://www.kitguru.net/peripherals/monitors/dominic-moass/aoc-ag276qsg2-review-1440p-360hz-g-sync-pulsar/"),
     ("Chip.de", 8, "https://www.chip.de/test/AOC-AGON-PRO-AG276QSG2-im-Test_186594666.html"),
     ("Trusted Reviews", 8, "https://www.trustedreviews.com/reviews/aoc-agon-pro-ag276qsg2"),
     ("Club386", 6, "https://www.club386.com/aoc-agon-pro-ag276qsg2-review/"),
     ("PC Games Hardware", None, "https://www.pcgameshardware.de/Monitor-Display-Hardware-154105/Tests/Fast-IPS-WQHD-Nvidia-G-Sync-Pulsar-360-Hz-Review-Test-Tech-1490836/")],
    "B0GFYHB2M5", "AOC Gaming Moniteur AG276QSG2 27 Pouce 360Hz Fast IPS Dalle, 1ms GtG, HDR10", 541.66,
    "Vous jouez à des FPS compétitifs sur une carte Nvidia et craignez le marquage des OLED.",
    "Vous privilégiez la qualité d'image : un OLED au même prix offre bien plus de contraste.")
ECR["samsung-odyssey-g81sf"] = E("e-gaming", "Samsung Odyssey OLED G8 G81SF", "27\" 4K UHD · QD-OLED · 240 Hz", "La 4K OLED mate",
    "Un 27 pouces 4K QD-OLED à 240 Hz avec traitement mat anti-reflets : une image très fine et confortable en pièce éclairée, au prix d'un peu de punch.",
    ["4K 240 Hz en QD-OLED", "Dalle mate qui limite les reflets", "Image très fine sur 27\""],
    ["Traitement mat qui ternit légèrement le contraste", "Testé sans note chiffrée"],
    ("27\" 4K", "240 Hz"),
    [(RT, None, "https://www.rtings.com/monitor/reviews/samsung/odyssey-oled-g81sf-s27fg810s"),
     ("Tweakers", None, "https://tweakers.net/reviews/13484/samsung-odyssey-oled-g81sf-27-inch-en-32-inch-extra-matte-oled-is-niet-in-alles-beter.html")],
    "B0DF8WSJ82", "Samsung Écran PC Gaming Odyssey OLED G8-G81SF, 27'', 4K (3840x2160), 240Hz, 0,03ms", 601.67,
    "Vous voulez un OLED 4K pour jouer dans une pièce lumineuse, sans reflets gênants.",
    "Vous jouez dans le noir et voulez le noir le plus profond : une dalle brillante fera mieux.")

# =====================================================================================================================
#                                                   CRÉATION & PHOTO
# =====================================================================================================================
ECR["asus-pa279crv"] = E("e-creation", "Asus ProArt PA279CRV", "27\" 4K UHD · IPS · USB-C 96 W", TOP,
    "Le meilleur rapport qualité-prix pour créer : dalle 4K bien calibrée, large gamme de couleurs, USB-C 96 W et pied réglable en tous sens.",
    ["Dalle 4K bien calibrée, gamme de couleurs étendue", "USB-C 96 W", "Pied réglable en tous sens, joystick pratique"],
    ["60 Hz seulement", "Contraste et HDR limités"],
    ("27\" 4K", "60 Hz"),
    [("TechRadar", 8, "https://www.techradar.com/pro/asus-proart-pa279crv-monitor-review"),
     ("Chip.de", 8, "https://www.chip.de/test/Asus-ProArt-PA279CRV-im-Test_185201334.html"),
     ("Les Numériques", 6, "https://www.lesnumeriques.com/moniteur/asus-proart-pa279crv-p74573/test.html"),
     ("PCWorld", None, "https://www.pcworld.com/article/1794810/asus-proart-pa279crv-review.html"),
     (RT, None, "https://www.rtings.com/monitor/reviews/asus/proart-display-pa279crv")],
    "B0BY2R4BHW", "ASUS Monitor LED IPS ProArt 27\" IPS, 4K UHD, Display Port, Vesa, HDR10, USB-C PD 96W", 329.75,
    "Vous retouchez des photos ou montez des vidéos et voulez un écran 4K précis sans payer un modèle pro.",
    "Vous voulez aussi jouer (60 Hz) ou un vrai rendu HDR.")
ECR["asus-pa32qcv"] = E("e-creation", "Asus ProArt PA32QCV", "32\" 6K · IPS · Thunderbolt 4", "La 6K",
    "Une dalle 6K sur 32 pouces à prix inédit, avec Thunderbolt 4 et un pied très fonctionnel : une netteté de texte et de photo spectaculaire.",
    ["Définition 6K ultra-nette", "Thunderbolt 4 et hub USB", "Bonne luminosité et belles couleurs"],
    ["Contraste modeste", "60 Hz, HDR peu convaincant"],
    ("32\" 6K", "60 Hz"),
    [("PCWorld", 8, "https://www.pcworld.com/article/2873124/asus-proart-pa32qcv-review.html"),
     ("PhotoTrend", 8, "https://phototrend.fr/2025/11/test-asus-proart-6k-pa32qcv/"),
     ("Tom's Hardware", 8, "https://www.tomshardware.com/monitors/asus-proart-pa32qcv-32-inch-6k-professional-monitor-review"),
     (RT, None, "https://www.rtings.com/monitor/reviews/asus/proart-display-6k-pa32qcv"),
     ("Tweakers", None, "https://tweakers.net/reviews/13848/asus-proart-pa32qcv-goedkoopste-6k-monitor-is-niet-zonder-compromis.html")],
    "B0FG8DB71B", "ASUS ProArt PA32QCV 32 Pouces 6K DCI-P3 Thunderbolt 4 Écran pour Mac", 1124.99,
    "Vous travaillez sur Mac ou retouchez de grandes images et voulez la plus grande netteté possible.",
    "Vous voulez un écran polyvalent pour jouer : 60 Hz seulement.")
ECR["asus-pa32ucdm"] = E("e-creation", "Asus ProArt PA32UCDM", "32\" 4K UHD · QD-OLED · 240 Hz · Thunderbolt 4", "L'OLED du créateur",
    "Un QD-OLED 4K calibré pour la création, excellent en SDR comme en HDR, avec Thunderbolt 4. Plus cher que les OLED gaming équivalents.",
    ["Qualité d'image OLED en SDR et HDR", "Nombreux modes colorimétriques", "Thunderbolt 4"],
    ["Plus cher que les OLED 4K gaming", "Connectique USB limitée"],
    ("32\" 4K", "240 Hz"),
    [("KitGuru", 8, "https://www.kitguru.net/peripherals/dominic-moass/asus-proart-pa32ucdm-review-4k-240hz-professional-oled/"),
     ("PCWorld", 6, "https://www.pcworld.com/article/2762020/asus-proart-pa32ucdm-review.html")],
    "B09T93CZVR", "ASUS ProArt PA32UCDM 32 Pouces 4K Écran Professionnel DCI-P3 OLED QD-OLED", 979.16,
    "Vous montez de la vidéo HDR ou retouchez des images et voulez la qualité OLED avec des modes pro.",
    "Vous faites surtout de la photo pour le web : un IPS calibré coûte trois fois moins.")
ECR["asus-pa27jcv"] = E("e-creation", "Asus ProArt PA27JCV", "27\" 5K · IPS · USB-C", "La 5K pour Mac",
    "Une dalle 5K de 27 pouces, la même finesse que les écrans Apple, avec une large gamme de couleurs : l'alternative au Studio Display.",
    ["Définition 5K, idéale sous macOS", "Large gamme de couleurs", "USB-C"],
    ["60 Hz", "Testé sans note chiffrée"],
    ("27\" 5K", "60 Hz"),
    [(RT, None, "https://www.rtings.com/monitor/reviews/asus/proart-display-pa27jcv")],
    "B08H4THPSB", "ASUS ProArt PA27JCV 27 Pouces 5K DCI-P3 USB-C Écran pour Mac", 536.37,
    "Vous travaillez sur Mac et voulez un texte aussi net que sur un écran Apple, pour bien moins cher.",
    "Vous êtes sous Windows en usage courant : la 4K suffit largement.")
ECR["asus-pa279cdv"] = E("e-creation", "Asus ProArt PA279CDV", "26,5\" 4K UHD · QD-OLED · 120 Hz · USB-C", "L'OLED 27\" pour créer",
    "Un QD-OLED 4K de 26,5 pouces au tarif contenu, avec HDR, 120 Hz, KVM et pied complet : une alternative OLED au Studio Display.",
    ["Dalle QD-OLED 4K", "120 Hz et HDR", "Connectique riche avec KVM"],
    ["Texte moins net qu'une dalle 5K", "Haut-parleurs faibles"],
    ("26,5\" 4K", "120 Hz"),
    [("Macworld", None, "https://macworld.com/article/3253774/asus-proart-oled-pa279cdv-review.html")],
    "B09BC332H6", "ASUS ProArt PA279CDV, Écran Pro, 27\" 4K 120Hz, QD-OLED, USB-C 96W, HDR10", 624.92,
    "Vous voulez le contraste de l'OLED pour la photo et la vidéo, sur un format 27\" de bureau.",
    "Vous laissez des fenêtres fixes affichées des heures durant (risque de marquage OLED).")
ECR["asus-pa27ucge"] = E("e-creation", "Asus ProArt PA27UCGE", "27\" 4K UHD · IPS · 160 Hz · sonde intégrée", "L'auto-calibrant",
    "Un 27 pouces 4K doté d'une sonde de calibration intégrée qui se recalibre seul, avec une excellente précision des couleurs et 160 Hz.",
    ["Sonde de calibration intégrée", "Précision des couleurs excellente", "160 Hz, KVM"],
    ["Uniformité de la luminosité perfectible", "Prix élevé"],
    ("27\" 4K", "160 Hz"),
    [("Profesional Review", 9.2, "https://www.profesionalreview.com/2025/05/30/asus-proart-pa27ucge-review/"),
     ("Photo Review", 8.8, "https://www.photoreview.com.au/reviews/monitors-digital-darkroom/asus-proart-display-pa27ucge/")],
    "B0F8W6VWRC", "ASUS ProArt PA27UCGE : 27, 4K IPS, 160Hz, 600 nits, 98% DCI-P3, Delta E1, colorimètre intégré", 565.82,
    "Vous êtes photographe ou vidéaste et voulez un écran toujours juste sans acheter de sonde.",
    "Vous n'avez pas besoin d'une colorimétrie certifiée : un PA279CRV fait l'essentiel pour moins cher.")
ECR["benq-pd2732u"] = E("e-creation", "BenQ PD2732U", "27\" 4K UHD · IPS · Thunderbolt 4", "Le Mac-friendly",
    "Un 4K de 27 pouces couvrant à la fois le DCI-P3 et l'Adobe RGB, avec Thunderbolt 4 et un mode couleurs Mac : très précis, un peu cher.",
    ["Large gamme de couleurs (P3 et Adobe RGB)", "Thunderbolt 4", "Modes couleurs adaptés au Mac"],
    ["Prix élevé pour une dalle 60 Hz", "Testé sans note chiffrée"],
    ("27\" 4K", "60 Hz"),
    [("Tom's Guide", None, "https://www.tomsguide.com/computing/monitors/benq-creative-pro-pd2732u-review"),
     ("MacGeneration", None, "https://www.macg.co/tests/2026/07/test-du-benq-creative-pro-pd2732u-un-moniteur-4k-de-27-pouces-qui-mise-tout-sur-les-couleurs-309945")],
    "B0H862B5P7", "BenQ PD2732U 27\" 4K Moniteur pour Mac avec Double Gamme de Couleurs 99%", 567.97,
    "Vous travaillez sur Mac en photo ou en impression et avez besoin de l'Adobe RGB.",
    "Vous cherchez un écran polyvalent pour jouer : 60 Hz seulement.")
ECR["dell-u2724d"] = E("e-creation", "Dell UltraSharp U2724D", "27\" QHD · IPS Black · 120 Hz", "Le contraste IPS Black",
    "La dalle IPS Black de Dell, plus contrastée qu'un IPS classique, avec 98 % du DCI-P3 et 120 Hz : un très bon écran pour la photo et le travail.",
    ["Contraste IPS Black", "Couleurs précises en sRGB et P3", "120 Hz, design sobre"],
    ["Pas d'USB-C alimenté sur cette version", "Pas de HDR ni de haut-parleurs"],
    ("27\" QHD", "120 Hz"),
    [("PCWorld", None, "https://www.pcworld.com/article/2178689/dell-ultrasharp-u2724d-review.html"),
     (MN, None, "https://monitornerds.com/dell-ultrasharp-u2724d-review/?utm_source=rss&utm_medium=rss&utm_campaign=dell-ultrasharp-u2724d-review")],
    "B0CMXGDK5S", "Dell UltraSharp 27 Écran PC - U2724D, QHD (2560x1440), 120Hz, IPS Black", 264.92,
    "Vous voulez des couleurs fiables et un bon contraste pour la photo, sans payer la 4K.",
    "Vous branchez un portable en USB-C : prenez la version U2724DE.")
ECR["asus-pa278qv"] = E("e-creation", "Asus ProArt PA278QV", "27\" QHD · IPS · 75 Hz", "Le ProArt d'entrée",
    "Le ProArt le plus abordable : QHD calibré d'usine (sRGB), pied réglable et connectique complète. Idéal pour débuter en retouche.",
    ["Calibré d'usine, couleurs sRGB justes", "Prix contenu", "Pied réglable en tous sens"],
    ["75 Hz seulement", "Gamme de couleurs limitée au sRGB"],
    ("27\" QHD", "75 Hz"),
    [("Les Numériques", 8, "https://www.lesnumeriques.com/moniteur-ecran-lcd/asus-proart-pa278qv-p61255/test.html"),
     ("Chip.de", 8, "https://www.chip.de/test/asus-proart-pa278qv-im-test_236989")],
    "B0886LBL8R", "ASUS ProArt PA278QV 27 Pouces 1440p Écran Professionnel", 217.19,
    "Vous débutez en photo ou en graphisme et voulez des couleurs justes pour un petit budget.",
    "Vous travaillez pour l'impression ou le cinéma, qui demandent une gamme de couleurs plus large.")
ECR["eizo-cg2700s"] = E("e-creation", "Eizo ColorEdge CG2700S", "27\" QHD · IPS · sonde intégrée", "La référence pro",
    "L'écran des laboratoires photo : sonde de calibration intégrée, uniformité contrôlée, garantie longue. Une précision de référence, à un prix de pro.",
    ["Précision et uniformité de référence", "Sonde de calibration intégrée", "Qualité de fabrication Eizo"],
    ["Très cher", "Définition QHD seulement"],
    ("27\" QHD", "60 Hz"),
    [("Fstoppers", None, "https://fstoppers.com/reviews/review-eizo-coloredge-cg-2700s-monitor-619533"),
     ("PRAD", None, "https://cdn.eizo.be/fileadmin/Media_Content/Awards/fr/ColorEdge/CG2700S/PRAD_Review_CG2700S_FR.pdf")],
    "B09ZQD9SHG", "Eizo ColorEdge CG2700S écran Plat de PC 68,6 cm (27\") 2560 x 1440 Pixels Wide Quad HD LED", 1666.64,
    "Vous êtes photographe professionnel et vos tirages doivent correspondre exactement à l'écran.",
    "Vous retouchez pour le web ou en amateur : un ProArt calibré suffit.")

# =====================================================================================================================
#                                                   ÉCRANS PORTABLES
# =====================================================================================================================
ECR["asus-mb169ck"] = E("e-portable", "Asus ZenScreen MB169CK", "15,6\" Full HD · IPS · USB-C", TOP,
    "Le second écran de voyage simple et pas cher : léger, alimenté et piloté par un seul câble USB-C, avec béquille intégrée et garantie de 3 ans.",
    ["Un seul câble USB-C", "Léger et compact, béquille 360°", "Prix très bas, garantie 3 ans"],
    ["Luminosité un peu juste", "Couleurs insuffisantes pour la retouche"],
    ("15,6\" Full HD", "60 Hz"),
    [("Basic Tutorials", 8.6, "https://basic-tutorials.de/tests/peripherie/asus-zenscreen-mb169ck/"),
     ("TechTest", None, "https://techtest.org/asus-zenscreen-mb169ck-test-portabler-156-zoll-monitor-fuer-99e/")],
    "B0DT4NRV5Z", "ASUS ZenScreen MB169CK 15.6 Pouces Écran Portable", 82.50,
    "Vous voulez un second écran à glisser dans le sac pour travailler en déplacement ou chez vous.",
    "Vous travaillez près d'une fenêtre ou retouchez des photos.")
ECR["asus-mb166c"] = E("e-portable", "Asus ZenScreen MB166C", "15,6\" Full HD · IPS · USB-C", "Le plus vendu",
    "Un écran portable très diffusé : fin, léger, branché en USB-C, livré avec sa housse-support. L'essentiel pour doubler l'écran d'un portable.",
    ["Très léger", "Branchement USB-C unique", "Housse qui sert de support"],
    ["Image un peu terne", "Support peu stable"],
    ("15,6\" Full HD", "60 Hz"),
    [("Creative Bloq", 8, "https://www.creativebloq.com/reviews/asus-zenscreen-mb166cr"),
     ("Digital Weekly", None, "https://www.digitweek.com/asus-zenscreen-mb166c-review/")],
    "B09P3SBQ8W", "ASUS ZenScreen MB166C 15.6 Pouces Écran Portable", 78.58,
    "Vous voulez un second écran léger au prix le plus bas pour le télétravail mobile.",
    "Vous voulez un pied stable et réglable.", scope="gamme")
ECR["asus-mb16acv"] = E("e-portable", "Asus ZenScreen MB16ACV", "15,6\" Full HD · IPS · USB-C", "L'antibactérien",
    "Un ZenScreen à traitement antibactérien et béquille intégrée, compatible USB-C et USB-A : pratique pour un usage partagé au bureau ou en classe.",
    ["Compatible USB-C et USB-A", "Traitement antibactérien", "Béquille intégrée"],
    ["Luminosité moyenne", "Tests anciens (modèle de la gamme MB16AC)"],
    ("15,6\" Full HD", "60 Hz"),
    [("Notebookcheck", None, "https://www.notebookcheck.com/Test-Asus-ZenScreen-MB16AC-15-6-FHD-IPS-Monitor.251642.0.html"),
     ("Allround-PC", None, "https://www.allround-pc.com/artikel/monitore/test-asus-zenscreen-mb16ac")],
    "B0914KHQ4G", "ASUS Zenscreen MB16ACV - Ecran PC portable 15.6\" FHD - Télétravail ou gaming", 139.71,
    "Vous partagez l'écran avec d'autres ou devez le brancher sur un ancien PC sans USB-C.",
    "Vous cherchez le meilleur rapport qualité-prix : le MB169CK fait aussi bien pour moins cher.", scope="gamme")
ECR["asus-mq149cd"] = E("e-portable", "Asus ZenScreen Duo OLED MQ149CD", "2 × 14\" OLED · WUXGA · USB-C", "Le double écran OLED",
    "Deux dalles OLED de 14 pouces reliées par une charnière : on les empile ou on les place côte à côte. Superbe, bien construit, mais cher.",
    ["Deux écrans OLED magnifiques", "Format livre polyvalent (paysage ou portrait)", "Construction aluminium"],
    ["Prix élevé", "Dalles brillantes, pas de haut-parleurs"],
    ("2 × 14\" WUXGA", "60 Hz"),
    [("Profesional Review", 8.7, "https://www.profesionalreview.com/2025/04/24/asus-zenscreen-duo-oled-mq149cd-review/"),
     ("Tom's Hardware", None, "https://www.tomshardware.com/monitors/portable-monitors/asus-zenscreen-duo-oled-mq149cd-review"),
     ("Digital Citizen", None, "https://www.digitalcitizen.life/asus-zenscreen-duo-oled-review/")],
    "B09K6Y85QH", "ASUS ZenScreen Duo OLED MQ149CD - Dual-OLED-Monitor - 35.6 cm (14\")", 490.83,
    "Vous voulez transformer n'importe quel portable en station multi-écrans, avec une image OLED.",
    "Vous avez un petit budget : deux écrans IPS classiques coûtent bien moins cher.")
ECR["asus-mq17qh"] = E("e-portable", "Asus ZenScreen Fold MQ17QH", "17,3\" OLED pliable · 2,5K · USB-C", "Le pliable",
    "Un grand écran OLED de 17,3 pouces qui se plie en deux pour le transport : unique et spectaculaire, mais très cher et encore perfectible.",
    ["Grand écran OLED qui se plie", "Image 2,5K très belle", "Format unique"],
    ["Prix très élevé", "Pli visible selon l'angle"],
    ("17,3\" 2,5K", "60 Hz"),
    [("Geeknetic", 8, "https://www.geeknetic.es/Review/2918/ASUS-ZenScreen-Fold-OLED-MQ17QH-Review.html"),
     ("IT Pro", 6, "https://www.itpro.com/hardware/monitors/asus-zenscreen-fold-oled-mq17qh-review-the-portable-monitor-your-small-business-cant-afford")],
    "B0DPL8F4MZ", "ASUS ZenScreen Fold MQ17QH Moniteur Portable 17,3, Quad HD OLED (2560 x 1920)", 1803.74,
    "Vous voulez un grand écran nomade sans compromis de taille, et le prix n'est pas un frein.",
    "Vous cherchez un rapport qualité-prix raisonnable.")
ECR["asus-mq16fc"] = E("e-portable", "Asus ZenScreen OLED MQ16FC", "16\" OLED · WUXGA 16:10 · USB-C", "L'OLED nomade",
    "Un écran portable OLED de 16 pouces au format 16:10, avec recharge du portable en transit : des couleurs et un contraste bien au-dessus des IPS d'entrée.",
    ["Dalle OLED au contraste infini", "Format 16:10 confortable", "Recharge du portable en transit"],
    ["Plus cher qu'un portable IPS", "Testé sans note chiffrée"],
    ("16\" WUXGA", "60 Hz"),
    [("Root Nation", None, "https://root-nation.com/en/pc-en/pc-monitors-en/en-asus-zenscreen-oled-mq16fc-review/")],
    "B0GR6B24HL", "ASUS Moniteur Portable ZenScreen OLED MQ16FC – Écran OLED WUXGA 16 Pouces au Format 16:10", 233.32,
    "Vous voulez un écran nomade aux belles couleurs pour la photo, la vidéo ou les présentations.",
    "Vous voulez seulement afficher des mails et des tableaux : un IPS à 80 € suffit.")
ECR["msi-pro-mp165-e6"] = E("e-portable", "MSI Pro MP165 E6", "15,6\" Full HD · IPS · 2 × USB-C", "Le petit prix bien équipé",
    "Un écran portable économique livré avec trépied, fixations VESA et pochette, avec deux USB-C : l'équipement d'un modèle plus cher.",
    ["Deux USB-C avec Power Delivery", "Trépied, VESA et pochette fournis", "Bonne luminosité pour le prix"],
    ["Couleurs et contraste moyens", "Construction plastique"],
    ("15,6\" Full HD", "60 Hz"),
    [("PCWorld", 8, "https://www.pcworld.com/article/2900743/msi-pro-mp165-e6-review.html"),
     ("TechRadar", 8, "https://www.techradar.com/pro/msi-pro-mp165-e6-portable-monitor-review"),
     ("Tom's Hardware", 6, "https://www.tomshardware.com/monitors/portable-monitors/msi-pro-mp165-e6-portable-monitor-review")],
    "B0FG7WJ4YC", "MSI Pro MP165 E6 Écran Professionnel 15.6\" FHD", 74.99,
    "Vous voulez un écran d'appoint très abordable, avec de quoi le poser ou le fixer partout.",
    "Vous retouchez des images : les couleurs sont trop moyennes.")
ECR["acer-pd163q"] = E("e-portable", "Acer PD163Q", "2 × 15,6\" Full HD · IPS · USB-C", "Le double écran pliant",
    "Deux écrans Full HD reliés et pilotés par un seul câble USB-C : on double ou triple la surface d'affichage d'un portable. Pratique, mais épais.",
    ["Deux écrans par un seul câble", "Nombreuses positions", "Écrans symétriques et bien appariés"],
    ["Luminosité et colorimétrie moyennes", "Bordures épaisses, pied fragile"],
    ("2 × 15,6\" Full HD", "60 Hz"),
    [("Presse-citron", 7, "https://www.presse-citron.net/test-acer-pd163q-le-double-ecran-transportable-pour-plus-de-productivite/"),
     ("Frandroid", 7, "https://www.frandroid.com/marques/acer/2610193_test-de-lacer-pd163q-un-double-ecran-portable-pour-le-double-de-productivite"),
     ("Clubic", 7, "https://www.clubic.com/test-produit-572283-test-acer-pd163q-le-double-ecran-externe-qui-va-booster-votre-productivite.html")],
    "B0DPXGSRNX", "Acer PD3 | Écran Portable Double | 15,6 Pouces | 2X FHD", 217.50,
    "Vous travaillez en déplacement sur des tableaux, du code ou de la veille et voulez trois écrans avec votre portable.",
    "Vous êtes sur Mac : la gestion des deux écrans à la fois y est mal prise en charge.")
ECR["viewsonic-va1655"] = E("e-portable", "ViewSonic VA1655", "15,6\" Full HD · IPS · USB-C 60 W", "Le plus complet",
    "Un écran portable bien équipé : deux USB-C avec recharge 60 W, mini-HDMI, haut-parleurs et joystick de menu. Un peu plus épais que la moyenne.",
    ["Deux USB-C (60 W) et mini-HDMI", "Haut-parleurs, menu au joystick", "Image nette et assez juste"],
    ["Contraste et couleurs modestes", "Plus lourd que certains rivaux"],
    ("15,6\" Full HD", "60 Hz"),
    [("PC Magazin", 8.9, "https://www.connect-living.de/testbericht/viewsonic-va1655-tragbarer-monitor-test-review-3205440.html"),
     ("Tom's Hardware", 6, "https://www.tomshardware.com/monitors/portable-monitors/viewsonic-va1655-portable-monitor-review"),
     ("PCWorld", 6, "https://www.pcworld.com/article/2853263/viewsonic-va1655-portable-monitor-review.html"),
     (MN, None, "https://monitornerds.com/viewsonic-va1655-review-affordable-1080p-ips-portable-monitor/?utm_source=rss&utm_medium=rss&utm_campaign=viewsonic-va1655-review-affordable-1080p-ips-portable-monitor")],
    "B09237LL5Q", "Viewsonic VA1655 Moniteur portable 40 cm (15,6 pouces) (Full HD, panneau IPS, mini HDMI, 2x USB-C)", 207.04,
    "Vous branchez aussi bien un portable qu'une console et voulez la recharge et le son intégrés.",
    "Vous cherchez le modèle le plus léger.", seller="vendeur tiers")
ECR["duex-max"] = E("e-portable", "Mobile Pixels Duex Max", "14,1\" Full HD · extension clipsée · USB-C", "L'écran qui se clipse",
    "Un écran de 14 pouces qui s'attache au dos du portable et coulisse sur le côté : la solution la plus compacte pour un double écran en voyage.",
    ["Se fixe directement sur le portable", "Coulisse et pivote (paysage, portrait)", "USB-C ou HDMI"],
    ["Alourdit l'écran du portable", "Testé sans note chiffrée"],
    ("14,1\" Full HD", "60 Hz"),
    [("Help Desk Geek", None, "https://helpdeskgeek.com/mobile-pixels-duex-max-portable-monitor-review/"),
     ("Keith Wee", None, "https://keithwee.com/duex-max-portable-monitor-review-2023-productivity-max/")],
    "B0C39RBB4K", "Mobile Pixels New Duex Max DS 14.1'' FHD 1080p Laptop Screen Extender, USB Type-C/HDMI", 208.14,
    "Vous travaillez dans le train ou en café et voulez un deuxième écran sans pied ni sac supplémentaire.",
    "Votre portable a un écran fragile ou une charnière légère : l'écran ajoute du poids.")

# =====================================================================================================================
#                                                   PETIT PRIX (< 200 €)
# =====================================================================================================================
ECR["aoc-q27g4x"] = E("e-lowcost", "AOC Gaming Q27G4X", "27\" QHD · Fast IPS · 180 Hz", TOP,
    "La bonne affaire du 27 pouces : QHD, 180 Hz, couleurs justes et pied réglable pour bien moins de 200 €. Peu de ports, HDR décoratif.",
    ["QHD et 180 Hz pour moins de 200 €", "Couleurs précises", "Pied ergonomique"],
    ["Peu de connectique, pas d'USB", "HDR peu lumineux"],
    ("27\" QHD", "180 Hz"),
    [("GadgetGear", 9, "https://www.gadgetgear.nl/2024/06/review-aoc-q27g4x-27-hoge-refreshrate-voor-iedereen/"),
     ("LeCafeDuGeek", 8, "https://lecafedugeek.fr/test-aoc-q27g4x-un-ecran-gamer-qui-a-tout-pour-plaire/"),
     ("Tom's Hardware", 8, "https://www.tomshardware.com/monitors/gaming-monitors/aoc-q27g4xy-qhd-smart-gaming-monitor-review"),
     ("Multiplayer.it", 7, "https://multiplayer.it/recensioni/aoc-q27g4x-recensione-monitor-27-pollici-quad-hd-prezzo-abbordabile.html"),
     ("Game-eXperience", 7, "https://game-experience.it/aoc-q27g4x-la-recensione-del-monitor-per-tutte-le-tasche/")],
    "B0GWDTNJN3", "AOC Gaming Moniteur Q27G4XFAD 27 Pouce 180Hz Fast IPS Dalle, 1ms GtG, HDR10", 133.32,
    "Vous voulez un 27\" QHD fluide pour jouer et travailler, au meilleur prix.",
    "Vous avez besoin d'un hub USB ou d'un port USB-C.", scope="gamme")
ECR["aoc-q27g4zr"] = E("e-lowcost", "AOC Gaming Q27G4ZR", "27\" QHD · Fast IPS · 260 Hz", "Le plus rapide",
    "Un QHD à 260 Hz bien calibré et lumineux, avec pied entièrement réglable : de la fluidité de compétition pour moins de 200 €.",
    ["260 Hz en QHD", "Dalle bien calibrée et lumineuse", "Pied réglable, input lag très faible"],
    ["Pas de port USB", "260 Hz uniquement en DisplayPort"],
    ("27\" QHD", "260 Hz"),
    [("KitGuru", 9, "https://www.kitguru.net/peripherals/monitors/dominic-moass/aoc-q27g4zr-review-budget-1440p-260hz/"),
     ("Basic Tutorials", 8.5, "https://basic-tutorials.de/tests/peripherie/aoc-gaming-q27g4zr-im-test/"),
     ("Les Numériques", 8, "https://www.lesnumeriques.com/moniteur/aoc-q27g4zr-p78457/test.html")],
    "B0GWDRVW5P", "AOC Gaming Moniteur Q27G4ZRAD 27 Pouce 260Hz Fast IPS Dalle, 1ms GtG, HDR400", 166.66,
    "Vous jouez à des jeux rapides et voulez le maximum de fluidité sans dépasser 200 €.",
    "Votre carte graphique ne dépasse pas 100 images par seconde : un 180 Hz suffit.", scope="gamme")
ECR["aoc-24g4zr"] = E("e-lowcost", "AOC Gaming 24G4ZR", "24\" Full HD · Fast IPS · 260 Hz", "Le 24\" e-sport",
    "Un 24 pouces Full HD à 260 Hz avec pied réglable en hauteur, pour moins de 100 € : le format préféré des joueurs compétitifs.",
    ["260 Hz pour moins de 100 €", "Pied réglable en hauteur", "Format 24\" idéal en e-sport"],
    ["Full HD seulement", "HDR anecdotique"],
    ("24\" Full HD", "260 Hz"),
    [("Basic Tutorials", 8.6, "https://basic-tutorials.de/tests/peripherie/aoc-gaming-24g4x/"),
     (MN, None, "https://monitornerds.com/aoc-24g4-review/?utm_source=rss&utm_medium=rss&utm_campaign=aoc-24g4-review")],
    "B0FR4VXQMV", "AOC Moniteur 24G4ZR 24 Pouce 260Hz Fast IPS Dalle, 1ms GtG, HDR10, G-Sync Compatible", 95.79,
    "Vous jouez en compétitif sur un petit budget et préférez un écran 24\".",
    "Vous travaillez aussi beaucoup dessus : un 27\" QHD sera plus confortable.", scope="gamme")
ECR["gigabyte-gs25f2"] = E("e-lowcost", "Gigabyte GS25F2", "25\" Full HD · IPS · 200 Hz", "Le moins cher",
    "Un 25 pouces Full HD à 200 Hz pour moins de 100 € : la fluidité d'un écran gaming au prix d'un écran de bureau.",
    ["200 Hz pour moins de 100 €", "Dalle IPS", "Format 25\" compact"],
    ["Pied seulement inclinable", "Testé sans note chiffrée"],
    ("25\" Full HD", "200 Hz"),
    [("TechBroll", None, "https://techbroll.com/2025/09/gigabyte-gs25f2-gaming-monitor-review.html")],
    "B0F19F9B2P", "GIGABYTE GS25F2 Écran Gaming 25\" FHD - 1920 x 1080, 200Hz, 1ms, 300 CD/m²", 98.58,
    "Vous débutez dans le jeu PC et voulez un écran fluide au plus petit prix.",
    "Vous voulez régler la hauteur de l'écran ou une image plus fine.")
ECR["gigabyte-gs27qca"] = E("e-lowcost", "Gigabyte GS27QCA", "27\" QHD incurvé · VA · 180 Hz", "L'incurvé pas cher",
    "Un 27 pouces QHD incurvé à dalle VA bien contrastée, très bon marché : immersif en jeu, avec une ergonomie minimale.",
    ["Contraste élevé (dalle VA)", "QHD incurvé très bon marché", "Texte net"],
    ["Pied seulement inclinable", "Légères traînées dans les scènes sombres"],
    ("27\" QHD", "180 Hz"),
    [("DisplayNinja", 8, "https://www.displayninja.com/gigabyte-gs27qc-review/"),
     (RT, 8, "https://www.rtings.com/monitor/reviews/gigabyte/gs27qc"),
     ("GizTele", 8, "https://www.giztele.com/gigabyte-gs27qc-monitor/"),
     ("Actu High-Tech", None, "https://www.actuhightech.com/test-du-moniteur-gaming-incurve-gigabyte-gs27qca-27-qhd/")],
    "B0DQ5J44NZ", "GIGABYTE GS27QCA 27\" Moniteur Gaming Incurvé QHD - 2560 x 1440, 180Hz, 1ms", 133.25,
    "Vous voulez un écran immersif et contrasté pour jouer et regarder des films, à petit prix.",
    "Vous jouez à des FPS très rapides : un IPS évite les traînées.", scope="gamme")
ECR["gigabyte-gs32qca"] = E("e-lowcost", "Gigabyte GS32QCA", "31,5\" QHD incurvé · VA · 180 Hz", "Le plus grand",
    "Un 32 pouces QHD incurvé à 180 Hz pour moins de 200 € : beaucoup de surface et d'immersion pour le prix.",
    ["Grande diagonale incurvée", "QHD 180 Hz", "Prix très bas pour un 32\""],
    ["Densité de pixels plus faible qu'un 27\"", "Testé sans note chiffrée"],
    ("31,5\" QHD", "180 Hz"),
    [("Noticias3D", None, "https://www.noticias3d.com/articulo/3919/p2/gigabyte-gs32qca-radeon-rx-9060-xt-review-pareja-avenida.html")],
    "B0DQ5T8M7J", "GIGABYTE GS32QCA 31,5\" Moniteur Gaming Incurvé QHD - 2560 x 1440, 180Hz, 1ms", 176.50,
    "Vous voulez un grand écran immersif pour jouer et regarder des vidéos sans gros budget.",
    "Vous lisez beaucoup de texte de près : le QHD sur 32\" est moins fin.")
ECR["dell-se2426hg"] = E("e-lowcost", "Dell SE2426HG", "24\" Full HD · Fast IPS · 240 Hz", "Le 240 Hz de marque",
    "Un 24 pouces 240 Hz signé Dell, avec garantie constructeur solide, pour moins de 100 € : simple et efficace.",
    ["240 Hz pour moins de 100 €", "Dalle Fast IPS", "Garantie Dell"],
    ["Pied basique", "Testé sans note chiffrée (variante SE2426HGS)"],
    ("24\" Full HD", "240 Hz"),
    [(RT, None, "https://www.rtings.com/monitor/reviews/dell/se2426hgs")],
    "B0GHQ2BPYJ", "Dell 24 Écran PC Gaming - SE2426HG, Full HD (1920x1080), 240Hz, Fast IPS", 90.83,
    "Vous voulez un écran rapide d'une grande marque pour un premier PC de jeu.",
    "Vous voulez régler la hauteur de l'écran.", scope="gamme")
ECR["asus-vg279qm5a"] = E("e-lowcost", "Asus TUF Gaming VG279QM5A", "27\" Full HD · Fast IPS · 240 Hz", "Le TUF 240 Hz",
    "Le successeur du VG279QM, référence du 27 pouces Full HD rapide : 240 Hz et Fast IPS pour un peu plus de 120 €.",
    ["240 Hz en Fast IPS", "Gamme TUF réputée", "Prix contenu"],
    ["Full HD un peu juste sur 27\"", "Notes surtout obtenues par le modèle précédent"],
    ("27\" Full HD", "240 Hz"),
    [("Les Numériques", 10, "https://www.lesnumeriques.com/moniteur-ecran-lcd/asus-vg279qm-p56789/test.html"),
     ("01net", 8, "https://www.01net.com/tests/test-de-l-asus-tuf-gaming-vg279qm-un-ecran-27-pouces-presque-parfait-pour-le-jeu-video-6459.html"),
     ("DisplayNinja", 8, "https://www.displayninja.com/asus-vg279qm-review/"),
     ("Actu High-Tech", None, "https://www.actuhightech.com/test-de-lecran-asus-tuf-vg279qm-performance-ultime-en-gaming/")],
    "B0FDBJBG7R", "ASUS TUF Gaming VG279QM5A 27 Pouces 240Hz Écran PC Gamer Fast IPS", 123.14,
    "Vous jouez à des jeux rapides et préférez un grand 27\" à un 24\".",
    "Vous voulez un texte fin pour travailler : préférez un QHD.", scope="gamme")
ECR["lenovo-legion-27q-10"] = E("e-lowcost", "Lenovo Legion 27Q-10", "27\" QHD · IPS · 240 Hz", "Le QHD 240 Hz",
    "Un 27 pouces QHD à 240 Hz avec certification Eyesafe pour moins de 150 € : une fiche technique rare à ce prix.",
    ["QHD à 240 Hz", "Certification Eyesafe (lumière bleue)", "Prix agressif"],
    ["Peu de tests publiés", "Testé sans note chiffrée"],
    ("27\" QHD", "240 Hz"),
    [("Croma Unboxed", None, "https://www.croma.com/unboxed/lenovo-legion-27q-10-gaming-monitor-review"),
     ("FoneArena", None, "https://www.fonearena.com/blog/473942/lenovo-legion-27q-10-review.html")],
    "B0FLQ62BSG", "Lenovo Legion 27Q-10 - Écran Gaming de 27\" QHD avec Eyesafe (IPS, 240Hz, 0.5ms)", 133.32,
    "Vous voulez la fluidité 240 Hz et la finesse QHD au prix d'un écran d'entrée de gamme.",
    "Vous voulez un modèle très éprouvé par la presse.")
ECR["iiyama-gb2771qsu"] = E("e-lowcost", "iiyama G-Master GB2771QSU", "27\" QHD · Fast IPS · 200 Hz · hub USB", "Le plus ergonomique",
    "Un QHD 200 Hz avec pied réglable en hauteur, haut-parleurs et hub USB : l'équipement complet de la gamme Red Eagle, réputée chez les joueurs.",
    ["Pied réglable en hauteur, pivot", "QHD 200 Hz", "Hub USB et haut-parleurs"],
    ["Notes obtenues par le modèle précédent (GB2770QSU)", "HDR décoratif"],
    ("27\" QHD", "200 Hz"),
    [("CowCotLand", 10, "https://www.cowcotland.com/articles/4503/iiyama-g-master-red-eagle-gb2770qsu-b6-un-excellent-ecran-qhd-qui-fait-le-job-mais.html"),
     ("KitGuru", 8, "https://www.kitguru.net/peripherals/dominic-moass/iiyama-gb2770qsu-1440p-165hz-monitor-review/"),
     ("CharlesTech", 7, "https://charlestech.fr/test-iiyama-g-master-gb2770qsu/"),
     (MN, None, "https://monitornerds.com/iiyama-gb2770qsu-review/")],
    "B0FV3CH9GZ", "iiyama Ecran G-Master Red Eagle, GB2771QSU-B1, Fast IPS, QHD@200Hz, 0.5ms, Haut-parleurs", 145.75,
    "Vous voulez un écran QHD rapide et bien réglable pour jouer et travailler, sans dépasser 150 €.",
    "Vous cherchez de l'USB-C pour brancher un portable.", scope="gamme")
