# -*- coding: utf-8 -*-
"""Catalogue Top 10 Geek — IMPRIMANTES (relevé du 09/10/2026).
50 imprimantes, 10 par usage. Chaque imprimante est en vente sur Amazon.fr au moment du relevé
(vendue par Amazon, ou à défaut par un vendeur tiers sur Amazon : champ seller) et couverte par au moins un test.
Les imprimantes sont surtout testées par les associations de consommateurs (Test-Achats, Que Choisir, Which?, Tænk),
qui publient leurs notes pour leurs seuls abonnés : ces tests sont cités et liés, sans note chiffrée.
Notes : (média, note sur 10 ou None, url). Même structure que catalog_ecrans.py."""

from catalog_ecrans import E, TOP

TA = "Test-Achats"
QC = "Que Choisir"
WH = "Which?"
RT = "RTINGS"


def ta(slug, i):
    return (TA, None, f"https://www.test-achats.be/hightech/imprimantes/comparateur/{slug}/16/{i}")


def qc(slug):
    return (QC, None, f"https://www.quechoisir.org/comparatif-imprimante-multifonction-n19/{slug}/")


def wh(slug):
    return (WH, None, f"https://www.which.co.uk/reviews/printers-and-ink/{slug}")


def rt(path):
    return (RT, None, f"https://www.rtings.com/printer/reviews/{path}")


IMP = {}

# =====================================================================================================================
#                                                   RÉSERVOIRS D'ENCRE
# =====================================================================================================================
IMP["epson-et-2862"] = E("i-reservoir", "Epson EcoTank ET-2862", "Multifonction A4 · réservoirs · Wi-Fi", TOP,
    "La porte d'entrée des réservoirs d'encre : on imprime des milliers de pages avec l'encre fournie, pour un coût à la page dérisoire. Lente et sans recto-verso automatique.",
    ["Coût à la page très bas", "Des milliers de pages avec l'encre fournie", "Compacte, Wi-Fi"],
    ["Lente, surtout en couleur", "Pas de recto-verso automatique ni de chargeur"],
    ("Jet d'encre à réservoirs", "Impression · copie · scan"),
    [ta("epson-ecotank-et-2862", 105058), qc("epson-ecotank-et-2862-p276698"),
     ("Expert Reviews", 8, "https://www.expertreviews.co.uk/printers/1415109/epson-ecotank-et-2850-review"),
     ("Tom's Guide", 8, "https://www.tomsguide.com/reviews/epson-ecotank-et-2850"),
     ("Laptop Mag", 8, "https://www.laptopmag.com/reviews/epson-ecotank-et-2850-all-in-one-printer")],
    "B0CPPLD6B2", "Epson EcoTank ET-2862 Imprimante à Réservoirs D'Encre | Maison & Petit Bureau | Wi-FI | A4", 169.69,
    "Vous imprimez régulièrement à la maison (devoirs, documents, quelques photos) et ne voulez plus racheter de cartouches.",
    "Vous imprimez de gros volumes en recto-verso ou avez besoin d'un chargeur de documents.", scope="gamme")
IMP["epson-et-2856"] = E("i-reservoir", "Epson EcoTank ET-2856", "Multifonction A4 · réservoirs · Wi-Fi", "La version blanche",
    "La déclinaison de la gamme ET-2850 : mêmes atouts (coût à la page très bas, encre pour des milliers de pages) et mêmes limites (lenteur, petit écran).",
    ["Coût à la page très bas", "Qualité d'impression soignée", "Compacte et sobre"],
    ["Impression lente", "Écran minuscule, pas de chargeur"],
    ("Jet d'encre à réservoirs", "Impression · copie · scan"),
    [("Expert Reviews", 8, "https://www.expertreviews.co.uk/printers/1415109/epson-ecotank-et-2850-review"),
     ("Tom's Guide", 8, "https://www.tomsguide.com/reviews/epson-ecotank-et-2850"),
     ("Laptop Mag", 8, "https://www.laptopmag.com/reviews/epson-ecotank-et-2850-all-in-one-printer"),
     ("Actualidad Gadget", 8, "https://www.actualidadgadget.com/epson-ecotank-2850-analisis-precio-caracteristicas/"),
     (RT, 6, "https://www.rtings.com/printer/reviews/epson/ecotank-et-2850")],
    "B09GFW8FLZ", "Imprimante multifonction A4 Wi-Fi EcoTank ET-2856 équipée de réservoirs d'encre", 291.07,
    "Vous voulez une imprimante à réservoirs simple pour la maison, sans abonnement ni cartouches.",
    "Vous cherchez la moins chère de la gamme : l'ET-2862 fait la même chose pour moins cher.", scope="gamme")
IMP["epson-et-2876"] = E("i-reservoir", "Epson EcoTank ET-2876", "Multifonction A4 · réservoirs · Wi-Fi", "Le recto-verso abordable",
    "Une EcoTank d'entrée de gamme plus récente, testée en laboratoire par Test-Achats et Que Choisir : l'économie des réservoirs dans un format compact.",
    ["Coût à la page très bas", "Compacte, Wi-Fi", "Testée par deux associations de consommateurs"],
    ["Vendue sur Amazon par un vendeur tiers", "Vitesse modeste"],
    ("Jet d'encre à réservoirs", "Impression · copie · scan"),
    [ta("epson-ecotank-et-2876", 105076), qc("epson-ecotank-et-2876-p276678")],
    "B0D1R8GR11", "Epson EcoTank ET-2876 Imprimante à Réservoirs D'encre | Maison & Petit Bureau | Wi-Fi | A4", 244.50,
    "Vous voulez une imprimante économique à l'usage pour toute la famille.",
    "Vous voulez acheter auprès d'Amazon directement : elle n'est proposée que par un vendeur tiers.", seller="vendeur tiers")
IMP["epson-et-3950"] = E("i-reservoir", "Epson EcoTank ET-3950", "Multifonction A4 · réservoirs · recto-verso", "Le télétravail",
    "Une EcoTank plus rapide avec recto-verso automatique et chargeur de documents : la bonne imprimante pour le télétravail, à l'encre très bon marché.",
    ["Recto-verso automatique", "Chargeur de documents", "Coût à la page très bas"],
    ["Prix d'achat élevé", "Photos correctes sans plus"],
    ("Jet d'encre à réservoirs", "Impression · copie · scan"),
    [ta("epson-et-3950", 125186), rt("epson/ecotank-et-3950"),
     ("PC-Welt", None, "https://www.pcwelt.de/?p=3014071")],
    "B0FKNG3MZ7", "Epson EcoTank ET-3950 Imprimante à Réservoirs D'Encre | Télétravail | Wi-FI | A4", 296.44,
    "Vous travaillez de chez vous et imprimez beaucoup de documents recto-verso.",
    "Vous imprimez seulement quelques pages par mois : l'achat ne sera pas amorti.")
IMP["epson-et-3956"] = E("i-reservoir", "Epson EcoTank ET-3956", "Multifonction A4 · réservoirs · recto-verso", "La variante télétravail",
    "Variante de l'ET-3950 testée à part par Test-Achats : recto-verso automatique, chargeur de documents et encre pour des milliers de pages.",
    ["Recto-verso automatique", "Chargeur de documents", "Coût à la page très bas"],
    ["Prix d'achat élevé", "Testée sans note publique"],
    ("Jet d'encre à réservoirs", "Impression · copie · scan"),
    [ta("epson-et-3956", 125183)],
    "B0FKSZCLFX", "Epson EcoTank ET-3956 Imprimante à Réservoirs D'Encre | Télétravail | Wi-FI | A4", 283.32,
    "Vous cherchez une imprimante de télétravail économique à l'usage, au meilleur prix du moment.",
    "Vous n'avez pas besoin du chargeur de documents ni du recto-verso.")
IMP["epson-et-4900"] = E("i-reservoir", "Epson EcoTank ET-4900", "Multifonction A4 · réservoirs · fax · Ethernet", "Le petit bureau",
    "Une EcoTank 4-en-1 avec fax, Ethernet et chargeur de documents : une vraie imprimante de petit bureau, au coût à la page minimal.",
    ["4-en-1 avec fax", "Ethernet et Wi-Fi", "Coût à la page très bas"],
    ["Plus encombrante", "Photos sans éclat"],
    ("Jet d'encre à réservoirs", "Impression · copie · scan · fax"),
    [ta("epson-ecotank-et-4900", 132659),
     ("Cybershack", None, "https://cybershack.com.au/computer/epson-ecotank-et-4900-review/")],
    "B0H1JJP668", "Epson EcoTank ET-4900 | Wi-FI et Ethernet | A4 | Impression, Copie, numérisation, fax", 308.37,
    "Vous gérez un petit bureau ou une activité indépendante et avez encore besoin du fax.",
    "Vous imprimez surtout des photos.")
IMP["epson-et-4956"] = E("i-reservoir", "Epson EcoTank ET-4956", "Multifonction A4 · réservoirs · recto-verso · Ethernet", "Le plus complet",
    "Une EcoTank très équipée (recto-verso, chargeur, Ethernet, écran tactile) qui imprime des milliers de pages. TechRadar la juge imbattable à ce prix.",
    ["Très bien équipée", "Coût à la page très bas", "Bonne qualité de documents"],
    ["Prix d'achat élevé", "Encombrante"],
    ("Jet d'encre à réservoirs", "Impression · copie · scan"),
    [ta("epson-et-4956", 125177),
     ("TechRadar", None, "https://www.techradar.com/pro/epson-ecotank-et-4950-ink-tank-printer-review"),
     rt("epson/ecotank-et-4950")],
    "B0FLPTJ427", "Epson EcoTank ET-4956 Imprimante à Réservoirs D'Encre | Télétravail | Wi-FI, Ethernet | A4", 351.66,
    "Vous voulez une imprimante de bureau complète que vous n'aurez presque jamais à recharger.",
    "Vous imprimez peu : une imprimante à cartouches coûtera moins cher à l'achat.", scope="gamme")
IMP["epson-et-4856"] = E("i-reservoir", "Epson EcoTank ET-4856", "Multifonction A4 · réservoirs · fax", "La valeur sûre",
    "La version 4-en-1 de la gamme ET-4850, très bien notée par la presse : documents de grande qualité, rendement de pages exceptionnel, photos un peu ternes.",
    ["Documents de grande qualité", "Rendement de pages exceptionnel", "Connectique complète"],
    ["Prix d'achat élevé", "Photos un peu ternes"],
    ("Jet d'encre à réservoirs", "Impression · copie · scan · fax"),
    [("SiteGeek", 8, "https://www.sitegeek.fr/article-technologie/test-epson-ecotank-4850/"),
     (RT, 8, "https://www.rtings.com/printer/reviews/epson/ecotank-et-4850"),
     ("IT Pro", 8, "https://www.itpro.co.uk/hardware/370336/epson-ecotank-review-an-above-average-mfp-with-low-running-costs"),
     ("TechRadar", 8, "https://www.techradar.com/pro/epson-ecotank-et-4850-review"),
     ("Chip.de", 8, "https://www.chip.de/test/Epson-EcoTank-ET-4850-im-Test_185863003.html")],
    "B09GFV83QX", "Imprimante multifonction A4 Wi-Fi EcoTank ET-4856 équipée de réservoirs d'encre", 487.93,
    "Vous imprimez beaucoup de documents de qualité au bureau et voulez oublier l'encre pendant des années.",
    "Vous imprimez surtout des photos : préférez une EcoTank Photo.", scope="gamme")
IMP["canon-g3570"] = E("i-reservoir", "Canon PIXMA G3570", "Multifonction A4 · réservoirs MegaTank · Wi-Fi", "L'alternative Canon",
    "La MegaTank compacte de Canon : coût à la page très bas, encres pigment/colorant pour des textes nets et des photos correctes.",
    ["Coût à la page très bas", "Compacte", "Bonne qualité de texte"],
    ["Vendue sur Amazon par un vendeur tiers", "Pas de recto-verso automatique"],
    ("Jet d'encre à réservoirs", "Impression · copie · scan"),
    [ta("canon-pixma-g3570", 116588), ("Tænk", None, "https://taenk.dk/test/printere/canon-pixma-g3570-0"),
     ("Que Choisir", None, "https://www.quechoisir.org/comparatif-imprimante-multifonction-n19/canon-pixma-g3571-p267222/")],
    "B0BN97QRPX", "Canon PIXMA G3570 Imprimante Jet d'encre Réservoir Compacte | Wi-FI", 259.78,
    "Vous préférez Canon et voulez une imprimante économique à l'usage pour la famille.",
    "Vous voulez acheter auprès d'Amazon directement : elle n'est proposée que par des vendeurs tiers.", seller="vendeur tiers")
IMP["epson-et-m1170"] = E("i-reservoir", "Epson EcoTank ET-M1170", "Monochrome A4 · réservoir · recto-verso", "Le noir et blanc à réservoir",
    "Une imprimante noir et blanc à réservoir d'encre : la rapidité et le recto-verso d'une laser, avec un coût à la page encore plus bas.",
    ["Coût à la page minimal", "Recto-verso automatique", "Wi-Fi"],
    ["Noir et blanc uniquement", "Vendue par un vendeur tiers, plus chère qu'ailleurs"],
    ("Jet d'encre à réservoir (noir)", "Impression seule"),
    [("Tænk", None, "https://taenk.dk/test/printere/epson-ecotank-et-m1170")],
    "B07QC7M2LZ", "EPSON EcoTank ET-M1170 | Imprimante jet d'encre monochrome - A4 sans fil, réservoir haute capacité", 479.19,
    "Vous imprimez beaucoup de textes en noir et blanc et voulez le coût par page le plus bas.",
    "Vous avez besoin de la couleur ou d'un scanner.", seller="vendeur tiers")

# =====================================================================================================================
#                                                   LASER MONOCHROME
# =====================================================================================================================
IMP["brother-dcp-l2620dw"] = E("i-laser-mono", "Brother DCP-L2620DW", "Multifonction laser N&B · recto-verso · Wi-Fi", TOP,
    "Le multifonction laser noir et blanc le plus raisonnable : rapide, recto-verso automatique, scanner et Wi-Fi, avec des toners à bon rendement.",
    ["Rapide, recto-verso automatique", "Impression, copie et scan", "Toners à bon rendement"],
    ["Noir et blanc uniquement", "Pas de chargeur de documents"],
    ("Laser monochrome", "Impression · copie · scan"),
    [ta("brother-dcp-l2620dw", 105066), qc("brother-dcp-l2620dw-p276790"),
     rt("brother/mfc-l2820dw-dcp-l2640dw-hl-l2480dw")],
    "B0CK2TN13B", "Brother DCP-L2620DW imprimante multifonction Laser A4 1200 x 1200 DPI 32 ppm Wifi", 149.17,
    "Vous imprimez surtout du texte (courriers, cours, factures) et voulez une machine rapide et fiable.",
    "Vous avez besoin de la couleur.")
IMP["brother-hl-l1240w"] = E("i-laser-mono", "Brother HL-L1240W", "Imprimante laser N&B · Wi-Fi · compacte", "La moins chère",
    "Une petite laser noir et blanc à moins de 100 € : elle imprime vite et proprement, sans fioritures (pas de scanner, recto-verso manuel).",
    ["Prix très bas", "Compacte", "Texte net et rapide"],
    ["Pas de scanner", "Recto-verso manuel"],
    ("Laser monochrome", "Impression seule"),
    [ta("brother-hl-l1240w", 122166), wh("brother-hl-l1240w")],
    "B0FFVQW7RZ", "Brother HL-L1240W Imprimante Laser Monochrome A4 compacte et Facile à Utiliser", 93.54,
    "Vous voulez juste imprimer des documents en noir et blanc, sans entretien, pour moins de 100 €.",
    "Vous devez aussi scanner ou photocopier.")
IMP["brother-dcp-l1642w"] = E("i-laser-mono", "Brother DCP-L1642W", "Multifonction laser N&B · Wi-Fi · compacte", "Le multifonction compact",
    "La version multifonction de l'entrée de gamme Brother : impression laser, copie et scan dans un format compact, testée par Clubic.",
    ["Impression, copie et scan", "Compacte", "Prix contenu"],
    ["Recto-verso manuel", "Volume mensuel modeste"],
    ("Laser monochrome", "Impression · copie · scan"),
    [("Clubic", None, "https://www.clubic.com/test-produit-580633-test-brother-dcp-l1642-l-imprimante-multifonction-monochrome-a-volume-moyen.html"),
     ta("brother-dcp-l1640w", 122161), qc("brother-dcp-l1640w-p285586")],
    "B0FFTS5Z7D", "Brother DCP-L1642W Imprimante Laser Multifonction 3-en-1 Monochrome A4 compacte", 124.99,
    "Vous voulez imprimer et scanner vos papiers en noir et blanc, dans un petit espace.",
    "Vous imprimez beaucoup en recto-verso.", scope="gamme")
IMP["brother-hl-l2865dw"] = E("i-laser-mono", "Brother HL-L2865DW", "Imprimante laser N&B · recto-verso · Wi-Fi · Ethernet", "La rapide",
    "Une laser noir et blanc rapide avec recto-verso automatique, Wi-Fi et Ethernet : la bonne imprimante de bureau, sans scanner.",
    ["Rapide", "Recto-verso automatique", "Wi-Fi et Ethernet"],
    ["Pas de scanner", "Noir et blanc uniquement"],
    ("Laser monochrome", "Impression seule"),
    [("TechRadar", None, "https://www.techradar.com/pro/brother-hl-l2865dw-printer-review"),
     ta("brother-hl-l2865dw", 111563), wh("brother-hl-l2865dw")],
    "B0D6WMH3YY", "Brother HL-L2865DW Imprimante Laser Monochrome Professionnelle | Impression Recto-Verso", 143.32,
    "Vous imprimez beaucoup de pages en noir et blanc dans un petit bureau.",
    "Vous devez scanner vos documents.")
IMP["brother-mfc-l2800dw"] = E("i-laser-mono", "Brother MFC-L2800DW", "Multifonction laser N&B · 4-en-1 · chargeur", "Le 4-en-1",
    "Un multifonction laser 4-en-1 avec chargeur de documents et recto-verso : tout ce qu'il faut pour un petit bureau, testé par trois associations de consommateurs.",
    ["Chargeur de documents", "Recto-verso, fax", "Rapide et fiable"],
    ["Noir et blanc uniquement", "Plus encombrant"],
    ("Laser monochrome", "Impression · copie · scan · fax"),
    [ta("brother-mfc-l2800dw", 105078), qc("brother-mfc-l2800dw-p276778"), wh("brother-mfc-l2800dw")],
    "B0CK2PVJSR", "Brother MFC-L2800DW Imprimante Multifonction 4 en 1 Laser Monochrome", 190.75,
    "Vous gérez des papiers en nombre (scans multipages, copies) et imprimez en noir et blanc.",
    "Vous avez besoin de la couleur.")
IMP["brother-mfc-l2835dw"] = E("i-laser-mono", "Brother MFC-L2835DW", "Multifonction laser N&B · 4-en-1 · chargeur", "Le 4-en-1 malin",
    "Un 4-en-1 laser noir et blanc avec chargeur et recto-verso, de la gamme MFC-L2820DW testée par RTINGS.",
    ["Chargeur de documents", "Recto-verso automatique", "Fax"],
    ["Noir et blanc uniquement", "Testé sans note chiffrée"],
    ("Laser monochrome", "Impression · copie · scan · fax"),
    [rt("brother/mfc-l2820dw-dcp-l2640dw-hl-l2480dw")],
    "B0CJRSY15B", "Brother MFC-L2835DW - Multifonction 4 en 1 Laser Noir et Blanc", 195.83,
    "Vous voulez un multifonction de bureau complet en noir et blanc.",
    "Vous imprimez peu : un modèle sans chargeur suffit.", scope="gamme")
IMP["brother-mfc-l2960dw"] = E("i-laser-mono", "Brother MFC-L2960DW", "Multifonction laser N&B · 4-en-1 · écran tactile", "Le plus équipé",
    "Le haut de la gamme laser noir et blanc de Brother : rapide, écran tactile, chargeur, recto-verso et fax. Pour les bureaux qui impriment beaucoup.",
    ["Rapide", "Écran tactile, chargeur", "Recto-verso, fax"],
    ["Prix plus élevé", "Noir et blanc uniquement"],
    ("Laser monochrome", "Impression · copie · scan · fax"),
    [ta("brother-mfc-l2960dw", 111565), wh("brother-mfc-l2960dw")],
    "B0D818BSFQ", "Brother MFC-L2960DW imprimante Multifonction Laser A4 1200 x 1200 DPI 34 ppm WiFi", 276.42,
    "Vous imprimez et scannez de gros volumes au bureau.",
    "Vous imprimez quelques pages par semaine.")
IMP["brother-dcp-l2665dw"] = E("i-laser-mono", "Brother DCP-L2665DW", "Multifonction laser N&B · chargeur · recto-verso", "Le scan recto-verso",
    "Un multifonction laser noir et blanc avec chargeur de documents, recto-verso et écran tactile, sans le fax.",
    ["Chargeur de documents", "Recto-verso automatique", "Écran tactile"],
    ["Noir et blanc uniquement", "Tests réalisés sur le DCP-L2660DW"],
    ("Laser monochrome", "Impression · copie · scan"),
    [ta("brother-dcp-l2660dw", 105079), qc("brother-dcp-l2660dw-p276786")],
    "B0CJRL253B", "Brother DCP-L2665DW - Imprimante Multifonction 3 en 1 Laser Monochrome", 195.83,
    "Vous scannez souvent des documents de plusieurs pages.",
    "Vous n'avez pas besoin de chargeur : le DCP-L2620DW coûte moins cher.", scope="gamme")
IMP["canon-lbp243dw-ii"] = E("i-laser-mono", "Canon i-SENSYS LBP243dw II", "Imprimante laser N&B · recto-verso · Wi-Fi", "L'alternative Canon",
    "Une laser noir et blanc rapide de Canon, avec recto-verso automatique et Wi-Fi, testée par Test-Achats et Which?.",
    ["Rapide", "Recto-verso automatique", "Wi-Fi et Ethernet"],
    ["Pas de scanner", "Prix un peu plus élevé que Brother"],
    ("Laser monochrome", "Impression seule"),
    [ta("canon-i-sensys-lbp243dw-ii", 125171), wh("canon-i-sensys-lbp243dw-ii"),
     ("Choice", None, "https://www.choice.com.au/products/electronics-and-technology/computers/scanners-and-printers/canon-i-sensys-lbp243dw-ii")],
    "B0FXN9CCVY", "Canon i-SENSYS LBP243dw II – Imprimante Laser Noir et Blanc sans Fil", 224.96,
    "Vous voulez une laser rapide et fiable pour le bureau, en noir et blanc.",
    "Vous devez scanner des documents.")
IMP["hp-laserjet-m234dw"] = E("i-laser-mono", "HP LaserJet M234dw", "Multifonction laser N&B · recto-verso · Wi-Fi", "Le HP",
    "Le multifonction laser noir et blanc de HP : compact, recto-verso automatique et application HP Smart. Attention aux toners propriétaires.",
    ["Compact", "Recto-verso automatique", "Application HP Smart pratique"],
    ["Toners HP chers", "Tests menés sur des variantes proches"],
    ("Laser monochrome", "Impression · copie · scan"),
    [ta("hp-laserjet-mfp-m234d", 114855), rt("hp/laserjet-mfp-m234sdwe")],
    "B08XNJ23VY", "HP LaserJet M234dw, 6GW99F, Imprimante Multifonction A4, Recto/Verso Automatique Noir et Blanc", 126.85,
    "Vous êtes habitué à l'écosystème HP et imprimez surtout du texte.",
    "Vous voulez des toners compatibles bon marché : HP les bloque parfois par mise à jour.", scope="gamme")

# =====================================================================================================================
#                                                   LASER COULEUR
# =====================================================================================================================
IMP["brother-mfc-l3760cdw"] = E("i-laser-couleur", "Brother MFC-L3760CDW", "Multifonction laser couleur · 4-en-1 · recto-verso", TOP,
    "Le multifonction laser couleur complet pour le petit bureau : impression, copie, scan recto-verso et fax, avec des toners à bon rendement.",
    ["4-en-1 avec chargeur", "Recto-verso automatique", "Bonne qualité de documents"],
    ["Encombrant", "Toners couleur chers à l'unité"],
    ("Laser couleur (LED)", "Impression · copie · scan · fax"),
    [("Chip.de", 8, "https://www.chip.de/test-kaufberatung/drucker-multifunktionsgeraete/brother-mfc-l3760cdw-im-test_6c122d8c-9c50-4a8e-94eb-cc686461d8cf.html"),
     ("Trusted Reviews", None, "https://www.trustedreviews.com/reviews/brother-mfc-l3760cdw")],
    "B0CJ9H2S7X", "Brother MFC-L3760CDW - Imprimante Laser Couleur Multifonction (Impression/Scan/Copie/Fax)", 324.99,
    "Vous imprimez des documents en couleur au bureau (devis, présentations) et scannez beaucoup.",
    "Vous imprimez des photos : une laser n'est pas faite pour ça.")
IMP["brother-hl-l3220cwe"] = E("i-laser-couleur", "Brother HL-L3220CWE", "Imprimante laser couleur · Wi-Fi · compacte", "La moins chère",
    "Une petite imprimante laser couleur abordable, éligible à l'abonnement toner EcoPro : idéale pour imprimer occasionnellement en couleur sans encre qui sèche.",
    ["Prix abordable", "Compacte", "Pas d'encre qui sèche"],
    ["Pas de scanner", "Recto-verso manuel"],
    ("Laser couleur (LED)", "Impression seule"),
    [("Trusted Reviews", None, "https://www.trustedreviews.com/reviews/brother-hl-l3220cwe"),
     rt("brother/hl-l3280cdw-hl-l3220cdw-hl-l3295cdw")],
    "B0CJC6V76D", "Brother HL-L3220CWE - Imprimante Laser Couleur - WiFi, USB - 18 Pages par Minute", 178.33,
    "Vous imprimez de temps en temps en couleur et en avez assez des cartouches jet d'encre sèches.",
    "Vous devez scanner ou imprimer beaucoup en recto-verso.", scope="gamme")
IMP["brother-hl-l3240cdw"] = E("i-laser-couleur", "Brother HL-L3240CDW", "Imprimante laser couleur · recto-verso · Ethernet", "La recto-verso",
    "La laser couleur compacte de Brother avec recto-verso automatique et Ethernet, testée par l'association danoise Tænk.",
    ["Recto-verso automatique", "Wi-Fi et Ethernet", "Compacte"],
    ["Pas de scanner", "Délai de livraison long chez Amazon"],
    ("Laser couleur (LED)", "Impression seule"),
    [("Tænk", None, "https://taenk.dk/test/printere/brother-hl-l3240cdw")],
    "B0CJ9DFM4R", "Brother HL-L3240CDW Imprimante Laser Couleur WiFi/USB/Ethernet Recto-Verso Automatique", 216.58,
    "Vous imprimez des documents couleur en recto-verso dans un petit bureau.",
    "Vous devez scanner des documents.")
IMP["canon-mf752cdw"] = E("i-laser-couleur", "Canon i-SENSYS MF752Cdw", "Multifonction laser couleur · recto-verso · écran tactile", "Le pro",
    "Un multifonction laser couleur de bureau rapide, avec scan recto-verso et grand écran tactile. La gamme MF750 est saluée pour la qualité de ses documents.",
    ["Documents de grande qualité", "Rapide, scan recto-verso", "Rendements élevés"],
    ["Photos granuleuses", "Toners couleur coûteux"],
    ("Laser couleur", "Impression · copie · scan"),
    [wh("canon-i-sensys-mf752cdw"),
     ("Digital Camera World", 8, "https://www.digitalcameraworld.com/reviews/canon-i-sensys-mf754cdw-review"),
     (RT, 8, "https://www.rtings.com/printer/reviews/canon/color-imageclass-mf753cdw-mf751cdw")],
    "B0FXNBVTP4", "Canon i-SENSYS MF752cdw Imprimante Laser Couleur Multifonction A4", 370.19,
    "Vous équipez un bureau qui imprime et scanne beaucoup de documents couleur.",
    "Vous imprimez peu : l'investissement est important.", scope="gamme")
IMP["canon-lbp647cdw"] = E("i-laser-couleur", "Canon i-SENSYS LBP647Cdw", "Imprimante laser couleur · recto-verso · Wi-Fi", "L'imprimante seule",
    "Une laser couleur de bureau sans scanner, rapide et compacte, avec recto-verso automatique.",
    ["Recto-verso automatique", "Wi-Fi et Ethernet", "Compacte"],
    ["Pas de scanner", "Testée sans note publique"],
    ("Laser couleur", "Impression seule"),
    [ta("canon-i-sensys-lbp647cdw", 125184), wh("canon-i-sensys-lbp647cdw")],
    "B0FXN9ZYK1", "Canon i-SENSYS LBP647cdw Imprimante Laser Couleur Recto Verso WiFi", 236.14,
    "Vous voulez imprimer en couleur au bureau, sans besoin de scanner.",
    "Vous scannez régulièrement.")
IMP["canon-mf664cdw"] = E("i-laser-couleur", "Canon i-SENSYS MF664Cdw", "Multifonction laser couleur · recto-verso · chargeur", "Le multifonction Canon",
    "Un multifonction laser couleur avec chargeur et recto-verso, testé en laboratoire par Test-Achats. Délai de livraison long chez Amazon.",
    ["Multifonction avec chargeur", "Recto-verso automatique", "Wi-Fi"],
    ["Délai de livraison long chez Amazon", "Testé sans note publique"],
    ("Laser couleur", "Impression · copie · scan"),
    [ta("canon-i-sensys-mf664cdw", 125181)],
    "B0FXNC7CNR", "Canon i-SENSYS MF664cdw Imprimante Laser Couleur Multifonction Scanner", 283.36,
    "Vous voulez un multifonction laser couleur complet à prix raisonnable.",
    "Vous avez besoin de l'imprimante rapidement.")
IMP["xerox-c320"] = E("i-laser-couleur", "Xerox C320", "Imprimante laser couleur · recto-verso · Wi-Fi", "La Xerox",
    "Une laser couleur rapide de Xerox, avec recto-verso automatique et Wi-Fi, testée par Test-Achats. Livraison longue chez Amazon.",
    ["Rapide", "Recto-verso automatique", "Wi-Fi et Ethernet"],
    ["Pas de scanner", "Délai de livraison long chez Amazon"],
    ("Laser couleur", "Impression seule"),
    [ta("xerox-c-320", 205884)],
    "B0D83BDYPF", "XEROX C320 DNI Imprimante laser couleur Wifi", 271.82,
    "Vous imprimez beaucoup de documents couleur et voulez de la vitesse.",
    "Vous devez scanner ou être livré rapidement.")
IMP["hp-color-laserjet-pro-3202dw"] = E("i-laser-couleur", "HP Color LaserJet Pro 3202dw", "Imprimante laser couleur · recto-verso · Wi-Fi", "La HP",
    "La laser couleur de HP pour le petit bureau : recto-verso automatique, Wi-Fi et Ethernet. Testée par Test-Achats, livraison longue chez Amazon.",
    ["Recto-verso automatique", "Wi-Fi et Ethernet", "Application HP Smart"],
    ["Toners HP chers", "Délai de livraison long chez Amazon"],
    ("Laser couleur", "Impression seule"),
    [ta("hp-color-laserjet-pro-3202dw", 108966)],
    "B0CWGPL92T", "HP Color LaserJet Pro 3202dw, 499R0F, Imprimante monofonction A4, Recto/Verso Automatique", 215.83,
    "Vous êtes équipé HP et imprimez des documents couleur au bureau.",
    "Vous voulez des consommables bon marché.")
IMP["hp-color-laser-179fnw"] = E("i-laser-couleur", "HP Color Laser MFP 179fnw", "Multifonction laser couleur · 4-en-1 · chargeur", "Le 4-en-1 compact",
    "Un petit multifonction laser couleur 4-en-1 avec chargeur de documents, testé par Test-Achats. Proposé sur Amazon par des vendeurs tiers.",
    ["4-en-1 avec chargeur", "Compact", "Wi-Fi"],
    ["Recto-verso manuel", "Vendu par des vendeurs tiers, plus cher qu'ailleurs"],
    ("Laser couleur", "Impression · copie · scan · fax"),
    [ta("hp-color-laser-mfp-179-fnw", 221248)],
    "B07RMJV1LT", "HP Color Laser MFP 179fnw, 4ZB97A, Imprimante multifonction couleur A4", 344.20,
    "Vous voulez un multifonction couleur compact pour un petit bureau.",
    "Vous imprimez beaucoup en recto-verso.", seller="vendeur tiers")
IMP["xerox-c230"] = E("i-laser-couleur", "Xerox C230", "Imprimante laser couleur · recto-verso · Wi-Fi", "La compacte",
    "La version imprimante seule de la Xerox C235 : compacte, rapide et de bonne qualité, mais avec un coût d'usage élevé. Livraison longue chez Amazon.",
    ["Compacte", "Bonne qualité d'impression", "Rapide"],
    ["Coût d'usage élevé", "Délai de livraison long chez Amazon"],
    ("Laser couleur", "Impression seule"),
    [("LeCafeDuGeek", 8, "https://lecafedugeek.fr/test-xerox-c235-limprimante-laser-parfaite-des-petits-espaces/"),
     ("Chip.de", 6, "https://www.chip.de/test-kaufberatung/drucker-multifunktionsgeraete/xerox-c235-im-test_1b3b0a2b-29a6-4ba0-b983-7d4c874a8117.html")],
    "B099X3HJQK", "Xerox C230dni A4 22ppm Couleur Imprimante Laser sans Fil avec Impression Recto-Verso", 240.83,
    "Vous avez peu de place et imprimez des documents couleur occasionnellement.",
    "Vous imprimez beaucoup : le coût par page est élevé.", scope="gamme")

# =====================================================================================================================
#                                                   PHOTO
# =====================================================================================================================
IMP["canon-selphy-cp1500"] = E("i-photo", "Canon Selphy CP1500", "Imprimante photo 10 × 15 · sublimation · Wi-Fi", TOP,
    "La référence des tirages 10 × 15 à la maison : sublimation thermique, photos plastifiées qui durent, coût par tirage parmi les plus bas des petites imprimantes.",
    ["Qualité de tirage excellente", "Photos plastifiées durables", "Coût par tirage bas"],
    ["Batterie en option", "Application perfectible"],
    ("Sublimation thermique", "Tirages 10 × 15"),
    [("PC Magazin", 9.5, "https://www.pc-magazin.de/testbericht/canon-selphy-cp1500-fotodrucker-test-review-3204235.html"),
     ("Creative Bloq", 8, "https://www.creativebloq.com/reviews/canon-selphy-cp1500"),
     ("Frandroid", None, "https://www.frandroid.com/marques/canon/1586624_test-de-la-canon-selphy-cp1500-une-imprimante-photo-efficace-et-un-poil-plus-rapide"),
     ("Trusted Reviews", None, "https://www.trustedreviews.com/reviews/canon-selphy-cp1500")],
    "B0DZDXF47Q", "Canon SELPHY CP1500 Imprimante Photo Portable WiFi + Ensemble de Papier", 133.32,
    "Vous voulez imprimer vos photos de vacances en 10 × 15 de qualité labo, chez vous.",
    "Vous voulez aussi imprimer des documents.")
IMP["canon-selphy-qx20"] = E("i-photo", "Canon Selphy QX20", "Imprimante photo de poche · sublimation · batterie", "La plus nomade",
    "Une imprimante photo de poche à sublimation : tirages nets, autocollants et résistants, en deux formats. L'autonomie et le coût par photo limitent l'usage intensif.",
    ["Tirages de qualité, résistants", "Deux formats, dos autocollant", "Très compacte"],
    ["Autonomie d'environ 20 tirages", "Pas de Bluetooth"],
    ("Sublimation thermique", "Mini tirages"),
    [("Labo Fnac", 8, "https://leclaireur.fnac.com/test/580989-test-canon-selphy-qx20-une-imprimante-photo-portable-efficace-et-polyvalente/"),
     ("Actualidad Gadget", 6, "https://www.actualidadgadget.com/canon-selphy-qx20-imprime-tus-fotos-donde-y-cuando-quieras-review/"),
     (RT, 5, "https://www.rtings.com/printer/reviews/canon/selphy-qx20"),
     ta("canon-selphy-qx-20", 190498),
     ("Digital Trends", None, "https://www.digitaltrends.com/computing/canon-selphy-qx20-review/")],
    "B0DG8LFP8V", "Canon SELPHY QX20 Imprimante Photo Portable Mini Sublimation 100 Ans", 107.50,
    "Vous voulez imprimer des souvenirs durables partout, en soirée ou en voyage.",
    "Vous imprimez beaucoup : le coût par tirage s'additionne.")
IMP["fujifilm-instax-link-wide"] = E("i-photo", "Fujifilm Instax Link Wide", "Imprimante instantanée · film Instax Wide", "L'instantané grand format",
    "Le charme de l'instantané Instax au grand format Wide, depuis le smartphone : couleurs réussies, mais un coût par photo élevé.",
    ["Format instantané large", "Couleurs réussies", "Très facile à utiliser"],
    ["Coût par photo élevé", "Recharge en micro-USB"],
    ("Instantané (film)", "Tirages Instax Wide"),
    [("01net", 8, "https://www.01net.com/tests/test-fujifilm-instax-link-wide-enfin-une-imprimante-nomade-pour-imprimer-vos-photos-en-version-instantanee-large-6689.html"),
     (RT, 5, "https://www.rtings.com/printer/reviews/fujifilm/instax-link-wide"),
     ("Les Numériques", None, "https://www.lesnumeriques.com/imprimante-photo-portable/fujifilm-instax-link-wide-p65671/test.html"),
     ta("fujifilm-instax-link-wide", 154016)],
    "B00JOBFVMI", "Instax Wide Link Gray", 125.16,
    "Vous aimez l'esthétique des photos instantanées et voulez les partager en grand format.",
    "Vous imprimez beaucoup : chaque photo coûte cher.")
IMP["fujifilm-instax-mini-link-3"] = E("i-photo", "Fujifilm Instax mini Link 3", "Imprimante instantanée · film Instax mini", "La plus fun",
    "La petite imprimante Instax mini à glisser dans la poche, avec une application ludique : idéale pour les fêtes et les ados, au coût par photo élevé.",
    ["Format de poche", "Application ludique", "Rendu instantané apprécié"],
    ["Petit format mini", "Coût par photo élevé"],
    ("Instantané (film)", "Tirages Instax mini"),
    [rt("fujifilm/instax-mini-link-3"), ta("fujifilm-instax-mini-link-3", 184723)],
    "B0DB8SQSRH", "instax Mini Link 3 imprimante Photo pour Smartphone Blanc Argile", 108.25,
    "Vous voulez imprimer des photos souvenirs en soirée ou en voyage, avec le style instantané.",
    "Vous voulez de vrais tirages 10 × 15.")
IMP["canon-zoemini-2"] = E("i-photo", "Canon Zoemini 2", "Imprimante de poche · papier Zink autocollant", "La sticker",
    "Une imprimante de poche sans encre (papier Zink) qui sort des photos autocollantes en quelques secondes : parfaite pour décorer, moins pour la qualité.",
    ["Ultra-compacte", "Photos autocollantes", "Sans encre ni cartouche"],
    ["Qualité Zink moyenne", "Coût par photo"],
    ("Zink (sans encre)", "Mini photos autocollantes"),
    [ta("canon-zoemini-2", 155338),
     ("Gathered", None, "https://www.gathered.how/arts-crafts/canon-zoemini-2-printer-review")],
    "B0BGT3G48W", "Canon ZOEMINI 2 Imprimante Photo Portable Bluetooth pour Téléphone", 83.29,
    "Vous voulez des photos autocollantes pour décorer un carnet, un agenda ou une chambre.",
    "Vous cherchez la qualité photo : une Selphy fera bien mieux.")
IMP["kodak-step"] = E("i-photo", "Kodak Step", "Imprimante de poche · papier Zink · Bluetooth", "La moins chère",
    "La petite imprimante Zink de Kodak, facile et bon marché : on imprime depuis le téléphone, sans encre. Qualité correcte, sans plus.",
    ["Prix bas", "Sans encre (Zink)", "Très légère"],
    ["Qualité d'image moyenne", "Bluetooth uniquement"],
    ("Zink (sans encre)", "Mini photos 5 × 7,6"),
    [("Tech Advisor", None, "https://www.techadvisor.com/article/723247/kodak-step-instant-printer-review.html"),
     ("PCMag", 8, "https://www.pcmag.com/reviews/kodak-step-slim-instant-mobile-photo-printer"),
     ("Tom's Guide", 8, "https://www.tomsguide.com/reviews/kodak-step-slim-mobile-photo-printer"),
     ("Digital Camera World", 6, "https://www.digitalcameraworld.com/reviews/kodak-step-slim-review")],
    "B094K165S1", "KODAK Step Imprimante Photo Mobile sans Fil avec Technologie Zinc (Rose)", 79.16,
    "Vous voulez offrir ou vous offrir une petite imprimante photo amusante, à petit prix.",
    "Vous attendez une qualité de tirage proche du labo.", scope="gamme")
IMP["hp-sprocket"] = E("i-photo", "HP Sprocket 2x3", "Imprimante de poche · papier Zink · Bluetooth", "La pionnière",
    "La Sprocket a popularisé les imprimantes de poche : simple, rapide, avec une application riche. Les tirages restent petits et coûteux.",
    ["Format de poche", "Application riche", "Sans encre"],
    ["Tirages petits et coûteux", "Qualité qui manque de détails"],
    ("Zink (sans encre)", "Mini photos 5 × 7,6"),
    [("Les Numériques", 8, "http://www.lesnumeriques.com/appareil-photo-instantane/hp-sprocket-p37853/test.html"),
     ("CNET", 6, "https://www.cnet.com/products/hp-sprocket-photo-printer/"),
     ta("hp-sprocket-200-1as86a", 145150)],
    "B07GFP7H8C", "HP Sprocket 2x3 Imprimante photo instantanée pour smartphone", 83.25,
    "Vous voulez imprimer des petites photos depuis le téléphone, avec retouches et cadres.",
    "Vous imprimez beaucoup : le papier Zink revient cher.", scope="gamme")
IMP["epson-et-8550"] = E("i-photo", "Epson EcoTank Photo ET-8550", "Multifonction A3+ · 6 encres · réservoirs", "La photo A3+",
    "Une imprimante photo à réservoirs à 6 encres qui imprime jusqu'à l'A3+ sans marge, pour un coût par tirage dérisoire. Chère à l'achat.",
    ["Photos détaillées et colorées", "A3+ sans marge", "Coût par tirage très bas"],
    ["Prix d'achat élevé", "Pas de chargeur de documents"],
    ("Jet d'encre à réservoirs (6 encres)", "Impression A3+ · copie · scan"),
    [("PC Magazin", 9.6, "https://www.pc-magazin.de/testbericht/epson-ecotank-et-8550-tintenstrahldrucker-a3-test-review-3204305.html"),
     (RT, 8, "https://www.rtings.com/printer/reviews/epson/ecotank-photo-et-8550"),
     ("Gear Diary", None, "https://geardiary.com/2026/08/04/epson-ecotank-photo-et-8550-review/")],
    "B08Y98MLMG", "Imprimante photo A3+ EcoTank ET-8550 avec réservoir d'encre et Wi-Fi", 583.32,
    "Vous êtes photographe amateur exigeant et imprimez beaucoup, y compris en grand format.",
    "Vous imprimez quelques photos par an : l'achat ne sera jamais amorti.")
IMP["epson-et-8500"] = E("i-photo", "Epson EcoTank Photo ET-8500", "Multifonction A4 · 6 encres · réservoirs", "La photo A4",
    "La version A4 de l'ET-8550 : 6 encres pour des photos très réussies et un coût par tirage minimal, saluée par Les Numériques.",
    ["Photos très réussies (6 encres)", "Coût par tirage très bas", "Multifonction"],
    ["Prix d'achat élevé", "Format limité à l'A4"],
    ("Jet d'encre à réservoirs (6 encres)", "Impression · copie · scan"),
    [("Les Numériques", 8, "https://www.lesnumeriques.com/imprimante/epson-ecotank-et-8500-copie-p63933/test.html"),
     ("Northlight Images", None, "https://www.northlight-images.co.uk/epson-et-8500-printer-review/"),
     wh("ecotank-et-8500")],
    "B08Y99KDP6", "Imprimante photo A4 EcoTank ET-8500 avec réservoir d'encre et Wi-Fi", 413.32,
    "Vous imprimez beaucoup de photos en A4 et voulez une qualité proche du labo.",
    "Vous imprimez surtout des documents.")
IMP["canon-pixma-ix6850"] = E("i-photo", "Canon PIXMA iX6850", "Imprimante A3+ · 5 encres · Wi-Fi", "L'A3+ abordable",
    "Une imprimante jet d'encre A3+ à 5 encres séparées, pour imprimer des photos et des affiches en grand format à prix contenu.",
    ["Impression jusqu'à l'A3+", "Prix d'achat contenu", "Encres séparées"],
    ["Cartouches coûteuses à l'usage", "Pas de scanner"],
    ("Jet d'encre (5 cartouches)", "Impression A3+ seule"),
    [("Expert Reviews", None, "https://www.expertreviews.co.uk/printers/53517/canon-pixma-ix6850-review"),
     ("Trusted Reviews", None, "https://www.trustedreviews.com/canon-pixma-ix6850-review"),
     ("TechRadar", None, "https://www.techradar.com/reviews/pc-mac/peripherals/printers-and-scanners/printers/canon-pixma-ix6850-wi-fi-office-printer-1240489/review")],
    "B00HZDLDK6", "Canon PIXMA iX6850 Imprimante WiFi (Noire) 5 Encres", 145.00,
    "Vous voulez imprimer de temps en temps des photos ou des affiches en A3.",
    "Vous imprimez beaucoup : le coût des cartouches grimpe vite.")

# =====================================================================================================================
#                                                   PETIT PRIX (< 150 €)
# =====================================================================================================================
IMP["canon-pixma-ts6550i"] = E("i-lowcost", "Canon PIXMA TS6550i", "Multifonction A4 · recto-verso · Wi-Fi", TOP,
    "Le jet d'encre familial le plus complet sous les 100 € : recto-verso automatique, scanner, Wi-Fi, testé par Test-Achats et Que Choisir.",
    ["Recto-verso automatique", "Multifonction Wi-Fi", "Prix bas"],
    ["Cartouches à racheter", "Coût par page plus élevé qu'un réservoir"],
    ("Jet d'encre (cartouches)", "Impression · copie · scan"),
    [ta("canon-pixma-ts6550i", 122170), qc("canon-pixma-ts6550i-p285566")],
    "B0GT28CL51", "Canon PIXMA TS6550i – Imprimante Jet d'Encre Multifonction Wi-FI – Impression Rapide Recto Verso", 74.99,
    "Vous imprimez un peu de tout à la maison (documents, photos) sans gros volume.",
    "Vous imprimez beaucoup : une imprimante à réservoirs sera plus économique.")
IMP["epson-xp-2200"] = E("i-lowcost", "Epson Expression Home XP-2200", "Multifonction A4 · Wi-Fi · compacte", "La moins chère",
    "L'imprimante multifonction la plus vendue pour presque rien : compacte et suffisante pour quelques pages par mois. Les cartouches coûtent vite plus cher que l'imprimante.",
    ["Prix plancher", "Très compacte", "Wi-Fi"],
    ["Cartouches chères à l'usage", "Lente, sans recto-verso automatique"],
    ("Jet d'encre (cartouches)", "Impression · copie · scan"),
    [wh("epson-expression-home-xp-2200"),
     ("Gadreview", None, "https://www.gadreview.com/review/epson-expression-xp-2200-review-451396")],
    "B0B8X457PN", "Epson Expression Home XP-2200 | Imprimante 3-en-1 - Impression, Numérisation, Copie - WiFi", 40.82,
    "Vous imprimez très rarement (une attestation, un billet) et voulez dépenser le moins possible.",
    "Vous imprimez chaque semaine : le prix des cartouches rattrapera vite l'économie.")
IMP["canon-pixma-ts3750i"] = E("i-lowcost", "Canon PIXMA TS3750i", "Multifonction A4 · Wi-Fi · compacte", "La compacte",
    "Une multifonction d'entrée de gamme compacte, éligible à l'abonnement d'encre de Canon, testée par Test-Achats et Which?.",
    ["Prix très bas", "Compacte", "Wi-Fi"],
    ["Cartouches chères à l'usage", "Pas de recto-verso automatique"],
    ("Jet d'encre (cartouches)", "Impression · copie · scan"),
    [ta("canon-pixma-ts3750i", 111567), wh("canon-pixma-ts3750i")],
    "B0DFZSGN7J", "Canon PIXMA TS3750i Wireless Colour All-in-One Inkjet Printer - A4, Copy, Scan", 41.62,
    "Vous voulez une petite imprimante d'appoint pour la maison.",
    "Vous imprimez beaucoup.")
IMP["canon-pixma-ts4151i"] = E("i-lowcost", "Canon PIXMA TS4151i", "Multifonction A4 · Wi-Fi · compacte", "L'entrée de gamme",
    "Une multifonction compacte d'entrée de gamme, testée par Test-Achats et (dans sa version TS4150i) par Que Choisir.",
    ["Prix très bas", "Compacte", "Wi-Fi"],
    ["Cartouches chères à l'usage", "Pas de recto-verso automatique"],
    ("Jet d'encre (cartouches)", "Impression · copie · scan"),
    [ta("canon-pixma-ts-4151-i", 190144), qc("canon-pixma-ts4150i-p285570")],
    "B0FY6RNQXL", "Canon PIXMA TS4151i Imprimante Jet d'encre Multifonction WiFi Compacte", 45.82,
    "Vous voulez une imprimante basique et pas chère pour la maison.",
    "Vous imprimez chaque semaine.")
IMP["epson-wf-2930dwf"] = E("i-lowcost", "Epson WorkForce WF-2930DWF", "Multifonction A4 · 4-en-1 · chargeur · fax", "Le 4-en-1 à 50 €",
    "Un 4-en-1 avec chargeur de documents et fax pour environ 50 € : le bon plan pour le télétravail léger, avec des cartouches à surveiller.",
    ["4-en-1 avec chargeur et fax", "Recto-verso", "Prix très bas"],
    ["Cartouches chères à l'usage", "Qualité photo moyenne"],
    ("Jet d'encre (cartouches)", "Impression · copie · scan · fax"),
    [ta("epson-workforce-wf-2930dwf", 89372), rt("epson/workforce-wf-2930"),
     ("Tænk", None, "https://taenk.dk/test/printere/epson-workforce-wf-2930dwf")],
    "B0B8X5H53X", "Epson Workforce WF-2930DWF | Imprimante 4-en-1 - Impression, Numérisation, Copie, Fax - WiFi", 49.99,
    "Vous télétravaillez un peu et devez scanner plusieurs pages d'un coup, pour un petit budget.",
    "Vous imprimez beaucoup de couleur.", scope="gamme")
IMP["canon-pixma-tr4755i"] = E("i-lowcost", "Canon PIXMA TR4755i", "Multifonction A4 · 4-en-1 · chargeur · fax", "Le 4-en-1 Canon",
    "Le 4-en-1 compact de Canon avec chargeur de documents et fax, testé en laboratoire par Test-Achats.",
    ["4-en-1 avec chargeur", "Compact", "Wi-Fi"],
    ["Cartouches chères à l'usage", "Lent"],
    ("Jet d'encre (cartouches)", "Impression · copie · scan · fax"),
    [ta("canon-pixma-tr4755i", 111570), ("Tænk", None, "https://taenk.dk/test/printere/canon-pixma-tr4755i"),
     wh("canon-pixma-tr4750i")],
    "B0FJSLRQMK", "Canon PIXMA TR4755i Imprimante Jet d'encre Multifonction", 58.32,
    "Vous avez besoin d'un fax et d'un chargeur pour vos papiers administratifs.",
    "Vous imprimez des photos.")
IMP["canon-pixma-ts7550i"] = E("i-lowcost", "Canon PIXMA TS7550i", "Multifonction A4 · recto-verso · Wi-Fi bi-bande", "La polyvalente",
    "Une multifonction familiale avec recto-verso automatique et Wi-Fi bi-bande, testée par Test-Achats et Que Choisir.",
    ["Recto-verso automatique", "Wi-Fi bi-bande", "Bonne polyvalence"],
    ["Cartouches à racheter", "Testée sans note publique"],
    ("Jet d'encre (cartouches)", "Impression · copie · scan"),
    [ta("canon-pixma-ts7550i", 122165), qc("canon-pixma-ts7550i-p285562")],
    "B0GT281VRC", "Canon PIXMA TS7550i – Imprimante compacte Jet d'Encre Multifonction Wi-FI 2,4/5 GHz", 66.66,
    "Vous voulez une imprimante familiale polyvalente qui fait le recto-verso.",
    "Vous imprimez de gros volumes.")
IMP["canon-pixma-ts7750i"] = E("i-lowcost", "Canon PIXMA TS7750i", "Multifonction A4 · recto-verso · écran", "La mieux équipée",
    "Une multifonction familiale bien équipée (recto-verso, écran, deux bacs) à moins de 100 €, testée par Test-Achats.",
    ["Recto-verso automatique", "Écran et deux bacs papier", "Wi-Fi"],
    ["Cartouches à racheter", "Testée sans note publique"],
    ("Jet d'encre (cartouches)", "Impression · copie · scan"),
    [ta("canon-pixma-ts7750i", 100495)],
    "B0CH8HQVKC", "Canon PIXMA TS7750i Imprimante Jet d'encre WiFi Recto Verso Auto", 87.42,
    "Vous voulez une imprimante familiale confortable, pour documents et photos.",
    "Vous imprimez beaucoup : passez aux réservoirs.")
IMP["canon-pixma-ts705a"] = E("i-lowcost", "Canon PIXMA TS705a", "Imprimante A4 · 5 encres · recto-verso", "La photo pas chère",
    "Une imprimante (sans scanner) à 5 encres séparées et recto-verso automatique : de jolies photos et des documents nets pour environ 50 €.",
    ["5 encres séparées, bonnes photos", "Recto-verso automatique", "Prix bas"],
    ["Pas de scanner", "Cartouches à racheter"],
    ("Jet d'encre (5 cartouches)", "Impression seule"),
    [wh("canon-pixma-ts705a"), rt("canon/pixma-ts702a")],
    "B09RN21CG7", "Canon PIXMA TS705a imprimante Jet d'encre, Noir", 54.17,
    "Vous voulez imprimer de jolies photos et des documents sans avoir besoin de scanner.",
    "Vous devez scanner ou photocopier.", scope="gamme")
IMP["brother-dcp-j1360dw"] = E("i-lowcost", "Brother DCP-J1360DW", "Multifonction A4 · recto-verso · Wi-Fi", "L'alternative Brother",
    "Une multifonction jet d'encre compacte de Brother avec recto-verso, testée par Test-Achats et Que Choisir. Délai de livraison de quelques semaines.",
    ["Recto-verso automatique", "Compacte", "Wi-Fi"],
    ["Délai de livraison chez Amazon", "Cartouches à racheter"],
    ("Jet d'encre (cartouches)", "Impression · copie · scan"),
    [ta("brother-dcp-j1360dw", 122163), qc("brother-dcp-j1360dw-p285578"),
     rt("brother/mfc-j1360dw-all-in-one")],
    "B0FB3YQKVJ", "Brother DCP-J1360DW Imprimante à Jet d'encre compacte sans Fil 3-en-1", 91.66,
    "Vous préférez Brother et voulez une multifonction compacte et polyvalente.",
    "Vous imprimez beaucoup de couleur.")
