# -*- coding: utf-8 -*-
"""Ordinateurs de bureau — SÉLECTION PROVISOIRE (29/09/2026).
Sert à préparer la structure avant le vrai comparatif (produits disponibles via l'affiliation).
Prix indicatifs arrondis ; notes presse uniquement quand un test noté a été relevé."""

CLUBIC_MINI = ("Comparatif mini-PC Clubic", "https://www.clubic.com/ordinateur-pc/mini-pc/comparatif/")

def P(notes, src, scope="modele"):
    return dict(scope=scope, src=src, notes=notes)

# id: dict(cat, short, ref, badge, price, fmt, cpu, verdict, strengths, weak, press)
DESK = {
    # ---------------- Bureautique ----------------
    "mac-mini-m4": dict(cat="d-bureau", short="Apple Mac mini M4", ref="Mac mini (2024) · puce M4 · 16 Go · 256 Go",
        badge="Le choix de la bande", price=699, fmt="Mini (12,7 cm de côté)", cpu="Apple M4",
        verdict="Minuscule, silencieux et très rapide : le meilleur ordinateur de bureau pour le prix, à condition d'accepter macOS.",
        strengths=["Performances de premier plan", "Totalement silencieux", "Format ultra-compact"],
        weak=["Pas de port USB-A", "SSD de 256 Go vite juste", "Bouton d'alimentation mal placé"],
        press=P([("Clubic", 9.0)], ("Test Clubic", "https://www.clubic.com/test-produit-555003-test-mac-mini-m4-on-a-teste-l-ordinateur-le-moins-cher-d-apple-c-est-un-must-have.html"))),
    "dell-slim-desktop": dict(cat="d-bureau", short="Dell Slim Desktop", ref="Tour compacte · Intel Core", badge="Le plus classique", price=649,
        fmt="Tour compacte", cpu="Intel Core i5 (selon config.)",
        verdict="Une tour compacte sans surprise, facile à faire évoluer, pour la bureautique familiale ou professionnelle.",
        strengths=["Évolutif (RAM, stockage)", "Connectique complète", "Format discret"], weak=[], press=None),
    "hp-slim-desktop": dict(cat="d-bureau", short="HP Slim Desktop", ref="Tour compacte · Intel Core / AMD Ryzen", badge="Le plus discret", price=599,
        fmt="Tour compacte", cpu="Intel Core i5 / Ryzen 5 (selon config.)",
        verdict="Un format fin qui se glisse sous un écran, suffisant pour le web, les mails et la bureautique.",
        strengths=["Encombrement réduit", "Prix contenu", "Nombreux ports USB"], weak=[], press=None),
    "lenovo-ideacentre-3": dict(cat="d-bureau", short="Lenovo IdeaCentre 3", ref="Tour · Intel Core / AMD Ryzen", badge="Le plus évolutif", price=649,
        fmt="Tour", cpu="Intel Core i5 / Ryzen 5 (selon config.)",
        verdict="Une tour familiale classique, qui laisse de la place pour ajouter un disque ou une carte graphique plus tard.",
        strengths=["Place pour évoluer", "Lecteur de cartes", "Bon rapport prix/équipement"], weak=[], press=None),
    # ---------------- Création ----------------
    "mac-studio-m4max": dict(cat="d-creation", short="Apple Mac Studio M4 Max", ref="Mac Studio (2025) · M4 Max", badge="Le choix de la bande", price=2499,
        fmt="Compact (19,7 cm de côté)", cpu="Apple M4 Max",
        verdict="Une puissance de station de travail dans un boîtier compact et quasi inaudible : la référence des créatifs.",
        strengths=["Performances CPU et GPU exceptionnelles", "Quasi silencieux", "Connectique très complète"],
        weak=["Mémoire et stockage non évolutifs", "Pas de Wi-Fi 7", "Bouton d'alimentation à l'arrière"],
        press=P([("Clubic", 9.0)], ("Test Clubic", "https://www.clubic.com/test-produit-557430-test-apple-mac-studio-2025-l-allie-supreme-des-createurs-de-contenus.html"))),
    "mac-mini-m4pro": dict(cat="d-creation", short="Apple Mac mini M4 Pro", ref="Mac mini (2024) · puce M4 Pro", badge="Le plus compact", price=1649,
        fmt="Mini (12,7 cm de côté)", cpu="Apple M4 Pro",
        verdict="La puissance du M4 Pro et le Thunderbolt 5 dans un boîtier de 12,7 cm : idéal pour la photo et le montage.",
        strengths=["Thunderbolt 5", "Très compact", "Silencieux"], weak=["Options de mémoire et stockage chères"], press=None),
    "hp-z2-mini-g1a": dict(cat="d-creation", short="HP Z2 Mini G1a", ref="Station de travail mini · AMD Ryzen AI Max", badge="La station mini", price=2500,
        fmt="Mini station de travail", cpu="AMD Ryzen AI Max (selon config.)",
        verdict="Une station de travail professionnelle au format mini, pensée pour la 3D et les gros fichiers.",
        strengths=["Format mini, puissance de station", "Certifications logiciels pros", "Beaucoup de mémoire possible"], weak=[], press=None),
    "thinkstation-p3-ultra": dict(cat="d-creation", short="Lenovo ThinkStation P3 Ultra", ref="Station de travail compacte · Intel Core · NVIDIA RTX", badge="Le plus évolutif", price=2200,
        fmt="Station compacte", cpu="Intel Core (selon config.) + GPU NVIDIA RTX pro",
        verdict="Une station compacte avec carte graphique professionnelle, taillée pour la vidéo et la 3D en entreprise.",
        strengths=["GPU professionnel", "Format compact", "Robustesse ThinkStation"], weak=[], press=None),
    "geekom-a9-max": dict(cat="d-creation", short="Geekom A9 Max", ref="Mini-PC · AMD Ryzen AI 9 HX", badge="Le mini-PC créatif", price=1699,
        fmt="Mini-PC", cpu="AMD Ryzen AI 9 HX 370",
        verdict="Un mini-PC très musclé, capable de retouche photo et de montage léger, dans un boîtier minuscule.",
        strengths=["Processeur Ryzen AI 9 puissant", "Très compact", "Connectique riche"], weak=["Pas de carte graphique dédiée"], press=None),
    # ---------------- Gaming ----------------
    "legion-tower-5i": dict(cat="d-gaming", short="Lenovo Legion Tower 5i", ref="Tour gaming · Intel Core · NVIDIA RTX", badge="Le choix de la bande", price=1599,
        fmt="Tour gaming", cpu="Intel Core i7 + RTX 5060 Ti / 5070 (selon config.)",
        verdict="Une tour gaming équilibrée, bien refroidie et évolutive, pour jouer en 1440p sans se ruiner.",
        strengths=["Bon refroidissement", "Évolutive", "Rapport prix/performances"], weak=[], press=None),
    "legion-tower-7i": dict(cat="d-gaming", short="Lenovo Legion Tower 7i", ref="Tour gaming haut de gamme · Intel Core Ultra · RTX", badge="Haut de gamme", price=2799,
        fmt="Tour gaming", cpu="Intel Core Ultra 9 + RTX 5080 (selon config.)",
        verdict="Le très haut de gamme de Lenovo : de quoi jouer en 4K et streamer en même temps.",
        strengths=["Très puissante", "Finition soignée", "Refroidissement liquide"], weak=["Prix élevé"], press=None),
    "omen-35l": dict(cat="d-gaming", short="HP Omen 35L", ref="Tour gaming · Intel Core / AMD Ryzen · RTX", badge="Le plus accessible", price=1499,
        fmt="Tour gaming", cpu="Core i7 / Ryzen 7 + RTX 5060 Ti (selon config.)",
        verdict="Une tour gaming sobre et évolutive, bon point d'entrée pour le 1080p et le 1440p.",
        strengths=["Design sobre", "Facile à faire évoluer", "Bon prix"], weak=[], press=None),
    "omen-45l": dict(cat="d-gaming", short="HP Omen 45L", ref="Tour gaming · refroidissement Cryo Chamber", badge="Le plus frais", price=2799,
        fmt="Grande tour gaming", cpu="Core i9 / Ryzen 9 + RTX 5080 (selon config.)",
        verdict="Une grande tour haut de gamme reconnaissable à sa chambre de refroidissement séparée.",
        strengths=["Refroidissement très efficace", "Très puissante", "Espace pour évoluer"], weak=["Encombrante", "Prix élevé"], press=None),
    "alienware-area51": dict(cat="d-gaming", short="Alienware Area-51", ref="Tour gaming (2025) · Intel Core Ultra 9 · RTX", badge="Le plus puissant", price=3999,
        fmt="Grande tour gaming", cpu="Intel Core Ultra 9 + RTX 5080 / 5090 (selon config.)",
        verdict="La vitrine d'Alienware : un monstre de puissance au design spectaculaire, pour ceux qui veulent le maximum.",
        strengths=["Puissance maximale", "Design spectaculaire", "Refroidissement généreux"], weak=["Prix très élevé", "Très encombrante"], press=None),
    # ---------------- Mini-PC ----------------
    "acemagic-kron-k1": dict(cat="d-mini", short="AceMagic Kron Mini K1", ref="Mini-PC · AMD Ryzen 5 7430U", badge="Le choix de la bande", price=299,
        fmt="Mini-PC", cpu="AMD Ryzen 5 7430U",
        verdict="Un vrai Ryzen 5 dans un boîtier de poche pour moins de 300 € : la bonne affaire des mini-PC.",
        strengths=["Ryzen 5 six cœurs", "Prix très bas", "Compact et silencieux"], weak=["Finition simple"],
        press=P([("Clubic", 7.0)], CLUBIC_MINI)),
    "beelink-eq14-mini": dict(cat="d-mini", short="Beelink EQ14", ref="Mini-PC · Intel N150", badge="Le plus économe", price=349,
        fmt="Mini-PC", cpu="Intel N150",
        verdict="Très sobre en énergie et silencieux : parfait comme PC de salon, serveur domestique ou poste bureautique.",
        strengths=["Consommation très faible", "Silencieux", "Alimentation intégrée"], weak=["Puissance limitée"],
        press=P([("Clubic", 7.0)], CLUBIC_MINI)),
    "nipogi-ak1plus": dict(cat="d-mini", short="NiPoGi AK1PLUS", ref="Mini-PC · Intel N95", badge="Le moins cher", price=279,
        fmt="Mini-PC", cpu="Intel N95",
        verdict="Le ticket d'entrée du mini-PC : suffisant pour le web et la vidéo, pas plus.",
        strengths=["Prix plancher", "Très compact"], weak=["Processeur N95 limité", "Finition basique"],
        press=P([("Clubic", 6.0)], CLUBIC_MINI)),
    "geekom-it13": dict(cat="d-mini", short="Geekom IT13 (2025)", ref="Mini-PC · Intel Core i9-13900HK", badge="Le plus puissant", price=579,
        fmt="Mini-PC", cpu="Intel Core i9-13900HK",
        verdict="Un Core i9 dans un mini-PC : de la puissance de PC de bureau pour une fraction de l'encombrement.",
        strengths=["Processeur Core i9", "Connectique complète", "Compact"], weak=["Ventilateur audible en charge"], press=None),
    "asus-nuc14-pro-ai": dict(cat="d-mini", short="Asus NUC 14 Pro AI", ref="Mini-PC · Intel Core Ultra", badge="Le plus pro", price=849,
        fmt="Mini-PC", cpu="Intel Core Ultra (Lunar Lake)",
        verdict="L'héritier des NUC d'Intel : finition pro, processeur récent et gestion d'entreprise.",
        strengths=["Finition premium", "Processeur récent et sobre", "Format très compact"], weak=["Prix élevé pour un mini-PC"], press=None),
    # ---------------- Tout-en-un ----------------
    "imac-m4": dict(cat="d-aio", short="Apple iMac 24\" M4", ref="iMac (2024) · puce M4 · écran 4,5K", badge="Le choix de la bande", price=1499,
        fmt="Tout-en-un 24\"", cpu="Apple M4",
        verdict="Le tout-en-un le plus abouti : un bel écran 4,5K, une puce M4 rapide et un design fin, sans fil qui dépasse.",
        strengths=["Écran 4,5K aux couleurs superbes", "Puce M4 performante", "Design très fin"],
        weak=["Contraste et angles de vision moyens (Labo Fnac)", "Mémoire et stockage non évolutifs"],
        press=P([("Labo Fnac", 8.0)], ("Test Labo Fnac", "https://leclaireur.fnac.com/test/591564-test-labo-du-apple-imac-m4-10-cores-16-go-une-formidable-machine-de-travail/"))),
    "hp-omnistudio-x": dict(cat="d-aio", short="HP OmniStudio X 31,5\"", ref="Tout-en-un 31,5\" · Intel Core Ultra", badge="Le plus grand écran", price=1799,
        fmt="Tout-en-un 31,5\"", cpu="Intel Core Ultra (selon config.)",
        verdict="Un très grand écran 4K dans un tout-en-un élégant, pour travailler confortablement sur plusieurs fenêtres.",
        strengths=["Écran 31,5\" 4K", "Design soigné", "Webcam et son de qualité"], weak=["Encombrant"], press=None),
    "yoga-aio-9i": dict(cat="d-aio", short="Lenovo Yoga AIO 9i", ref="Tout-en-un 32\" 4K · Intel Core", badge="Le plus créatif", price=1899,
        fmt="Tout-en-un 32\"", cpu="Intel Core i9 (selon config.)",
        verdict="Un tout-en-un 32 pouces 4K aux couleurs fidèles, pensé pour les créatifs qui veulent un bureau épuré.",
        strengths=["Écran 32\" 4K fidèle", "Puissant", "Pied réglable"], weak=["Prix élevé"], press=None),
    "dell-24-aio": dict(cat="d-aio", short="Dell 24 Tout-en-un", ref="Tout-en-un 24\" Full HD · Intel Core", badge="Le plus accessible", price=799,
        fmt="Tout-en-un 24\"", cpu="Intel Core i5 (selon config.)",
        verdict="Un tout-en-un simple et abordable pour la famille : on le pose, on le branche, c'est prêt.",
        strengths=["Prix accessible", "Installation immédiate", "Webcam intégrée"], weak=["Écran Full HD seulement"], press=None),
    "hp-24-aio": dict(cat="d-aio", short="HP 24 Tout-en-un", ref="Tout-en-un 24\" Full HD", badge="Le petit prix", price=699,
        fmt="Tout-en-un 24\"", cpu="Intel Core / AMD Ryzen (selon config.)",
        verdict="Le tout-en-un d'entrée de gamme pour les usages du quotidien : web, visio, bureautique.",
        strengths=["Petit prix", "Encombrement réduit", "Clavier et souris fournis"], weak=["Écran Full HD seulement"], press=None),
}

DCATS = [
    dict(key="d-bureau", slug="bureautique", label="Bureautique", h="Bureautique", tag="Fiable et discret", color="var(--cat-bureau)", cls="f-bureau", badge="bureautique",
         h1='Les meilleurs ordinateurs de bureau pour la <span class="flash">bureautique</span>',
         intro="Pour le travail et la famille, un ordinateur de bureau doit être fiable, silencieux et facile à faire évoluer."),
    dict(key="d-creation", slug="creation", label="Création", h="Création &amp; station de travail", tag="Puissance au calme", color="var(--cat-creation)", cls="f-creation", badge="creation",
         h1='Les meilleurs ordinateurs de bureau pour la <span class="flash">création</span>',
         intro="Photo, vidéo, 3D : le fixe reste imbattable pour la puissance soutenue, le silence et le nombre d'écrans branchés."),
    dict(key="d-gaming", slug="gaming", label="Gaming", h="PC gamer fixe", tag="Puissance maximale", color="var(--cat-gaming)", cls="f-gaming", badge="gaming",
         h1='Les meilleurs <span class="flash">PC gamer fixes</span> prêts à jouer',
         intro="À budget égal, une tour gaming va plus loin qu'un portable : plus de puissance, moins de bruit, et des pièces que l'on peut changer."),
    dict(key="d-mini", slug="mini-pc", label="Mini-PC", h="Mini-PC", tag="Tout petit, très malin", color="var(--cat-lowcost)", cls="f-lowcost", badge="mini-pc",
         h1='Les meilleurs <span class="flash">mini-PC</span>',
         intro="Pas plus gros qu'un livre, un mini-PC fixé derrière l'écran remplace une tour pour la plupart des usages."),
    dict(key="d-aio", slug="tout-en-un", label="Tout-en-un", h="Tout-en-un", tag="Un seul câble", color="var(--cat-poly)", cls="f-polyvalent", badge="polyvalent",
         h1='Les meilleurs ordinateurs <span class="flash">tout-en-un</span>',
         intro="L'écran et l'ordinateur ne font qu'un : idéal pour un bureau épuré, un coin famille ou un poste d'accueil."),
]
