# -*- coding: utf-8 -*-
"""Guides d'achat « Comment choisir » — écrans PC et imprimantes (09/10/2026)."""

GUIDES_NEW = {
# ===================================================================== ÉCRANS
"e-bureau": dict(
    titre="Comment choisir un écran pour la bureautique",
    intro="Pour travailler des heures devant un écran, misez sur <b>la définition, le confort visuel et la connectique</b>. La fréquence et le HDR passent au second plan.",
    criteres=[
        ("Taille et définition", "24 pouces en Full HD pour un petit bureau, 27 pouces en QHD pour le confort, 27 à 32 pouces en 4K pour un texte très fin et plusieurs fenêtres côte à côte."),
        ("Dalle", "L'IPS offre des couleurs stables sous tous les angles. Le VA contraste davantage mais perd en couleurs de biais. Les dalles IPS Black combinent les deux."),
        ("USB-C", "Avec un portable, un port USB-C qui transmet l'image et recharge (65 W ou plus) remplace le chargeur et la station d'accueil : un seul câble à brancher."),
        ("Ergonomie", "Un pied réglable en hauteur évite les douleurs de nuque. Un traitement antireflet et un rétroéclairage sans scintillement reposent les yeux."),
    ],
    pieges=["Le Full HD sur 27 pouces : le texte paraît granuleux, préférez le QHD.",
            "Un USB-C qui ne transmet pas l'image ou ne recharge pas assez le portable : vérifiez la puissance indiquée.",
            "Les pieds seulement inclinables, inconfortables pour une longue journée."],
    budget=[("100 – 200 €", "24 ou 27 pouces Full HD ou QHD, l'essentiel."), ("250 – 400 €", "4K ou USB-C complet : le confort au quotidien.")],
),
"e-gaming": dict(
    titre="Comment choisir un écran gaming",
    intro="La bonne fréquence dépend de votre carte graphique et de vos jeux. Depuis deux ans, <b>l'OLED</b> est devenu abordable et domine les tests grâce à son contraste et sa réactivité.",
    criteres=[
        ("Définition", "QHD sur 27 pouces pour la majorité des joueurs ; 4K si votre carte graphique est très puissante ; Full HD sur 24 pouces pour l'e-sport."),
        ("Fréquence", "144 à 180 Hz pour jouer confortablement, 240 Hz et plus pour les jeux compétitifs. Inutile si votre PC n'affiche pas autant d'images par seconde."),
        ("Dalle", "L'OLED (QD-OLED ou WOLED) offre un contraste infini et une réactivité instantanée. L'IPS rapide reste moins cher et ne craint pas le marquage."),
        ("Synchronisation", "G-Sync ou FreeSync évitent les déchirures d'image : vérifiez la compatibilité avec votre carte graphique."),
    ],
    pieges=["Un 240 Hz branché sur un PC qui ne dépasse pas 100 images par seconde.",
            "Le HDR « 400 » des écrans LCD d'entrée de gamme, peu convaincant.",
            "Afficher des heures durant des éléments fixes sur un OLED sans activer les protections anti-marquage."],
    budget=[("150 – 300 €", "QHD IPS rapide, excellent rapport qualité-prix."), ("350 – 600 €", "OLED QHD 240 Hz et plus."), ("600 € et plus", "OLED 4K, 32 pouces ou 500 Hz.")],
),
"e-creation": dict(
    titre="Comment choisir un écran pour la photo et la création",
    intro="Pour retoucher, l'écran doit afficher les couleurs telles qu'elles seront imprimées ou publiées. <b>Calibration, gamme de couleurs et uniformité</b> comptent plus que tout.",
    criteres=[
        ("Gamme de couleurs", "100 % sRGB pour le web, une large couverture DCI-P3 pour la vidéo, Adobe RGB pour l'impression photo professionnelle."),
        ("Calibration", "Un écran calibré d'usine (Delta E < 2) est utilisable tout de suite. Les modèles haut de gamme intègrent une sonde qui se recalibre seule."),
        ("Définition", "4K sur 27 pouces est la norme ; 5K et 6K offrent une finesse proche des écrans Apple, appréciée sur Mac."),
        ("Connectique", "Thunderbolt ou USB-C avec charge pour brancher un portable, et un hub USB pour les disques et lecteurs de cartes."),
    ],
    pieges=["Les modes « vifs » d'usine, flatteurs mais faux : passez en mode sRGB ou calibré.",
            "Un écran à large gamme de couleurs sans mode sRGB : les images web paraîtront sursaturées.",
            "Négliger l'uniformité de la dalle sur les grands formats."],
    budget=[("200 – 350 €", "QHD ou 4K calibré sRGB pour bien débuter."), ("500 – 1 000 €", "4K large gamme, OLED ou 6K."), ("1 500 € et plus", "Les références avec sonde intégrée.")],
),
"e-portable": dict(
    titre="Comment choisir un écran portable",
    intro="Un écran portable double la surface de travail d'un ordinateur portable. Le critère n° 1 : <b>pouvoir le brancher avec un seul câble USB-C</b> qui transmet l'image et l'alimentation.",
    criteres=[
        ("Connexion", "Vérifiez que votre portable a un port USB-C compatible DisplayPort. Sinon, il faut un modèle avec mini-HDMI et une alimentation séparée."),
        ("Taille et poids", "14 pouces pour voyager léger, 15,6 à 16 pouces pour le confort. Comptez entre 600 g et 1 kg."),
        ("Dalle", "L'IPS Full HD suffit pour la bureautique ; l'OLED offre de bien plus belles couleurs pour la photo et la vidéo."),
        ("Support", "Une béquille intégrée ou une housse-support : c'est ce qui fait la différence au quotidien."),
    ],
    pieges=["Les écrans peu lumineux, inutilisables près d'une fenêtre.",
            "Un portable dont l'USB-C ne fournit pas assez d'énergie : l'écran baisse sa luminosité ou s'éteint.",
            "Les modèles sans marque aux caractéristiques invérifiables."],
    budget=[("70 – 150 €", "IPS Full HD 15,6 pouces."), ("200 – 500 €", "OLED, double écran ou formats originaux.")],
),
"e-lowcost": dict(
    titre="Comment choisir un écran à moins de 200 €",
    intro="Sous 200 €, on trouve d'excellents écrans de jeu et de travail. Le secret : <b>viser le QHD en 27 pouces</b> et accepter une connectique et un HDR basiques.",
    criteres=[
        ("Définition", "En 27 pouces, visez le QHD : il est désormais accessible sous 150 €. Le Full HD reste pertinent en 24 ou 25 pouces."),
        ("Fréquence", "180 Hz est devenu courant à ce prix, 240 Hz et plus pour les joueurs compétitifs."),
        ("Pied", "Un pied réglable en hauteur est rare à ce prix : c'est un vrai plus pour le confort."),
        ("Dalle", "L'IPS pour des couleurs stables, le VA (souvent incurvé) pour le contraste et les films."),
    ],
    pieges=["Les fiches techniques gonflées des marques inconnues (« 1 ms », « HDR ») sans test indépendant.",
            "Les écrans sans port DisplayPort, limités en fréquence via HDMI.",
            "Le Full HD en 27 pouces, au texte granuleux."],
    budget=[("80 – 130 €", "24 ou 27 pouces Full HD rapide."), ("130 – 200 €", "27 pouces QHD 180 à 260 Hz.")],
),
# ===================================================================== IMPRIMANTES
"i-reservoir": dict(
    titre="Comment choisir une imprimante à réservoirs d'encre",
    intro="Une imprimante à réservoirs coûte plus cher à l'achat mais <b>l'encre fournie suffit pour des milliers de pages</b>, et les recharges ne coûtent que quelques euros. Elle devient rentable dès que l'on imprime régulièrement.",
    criteres=[
        ("Volume d'impression", "À partir de quelques dizaines de pages par mois, le réservoir est gagnant. En dessous, une imprimante à cartouches bon marché suffit."),
        ("Fonctions", "Recto-verso automatique et chargeur de documents pour le télétravail ; fax et Ethernet pour le petit bureau."),
        ("Usage photo", "Les modèles à 4 encres impriment correctement les photos ; les EcoTank Photo à 6 encres font beaucoup mieux."),
        ("Vitesse", "Les réservoirs d'entrée de gamme sont lents. Si vous imprimez beaucoup d'un coup, visez un modèle de milieu de gamme."),
    ],
    pieges=["Payer 300 € une imprimante pour imprimer trois pages par mois.",
            "Les modèles sans recto-verso automatique pour le télétravail.",
            "Laisser l'imprimante inutilisée des mois : même avec un réservoir, les buses peuvent sécher."],
    budget=[("170 – 250 €", "Multifonction simple, coût à la page minimal."), ("280 – 500 €", "Recto-verso, chargeur, fax : la machine de bureau.")],
),
"i-laser-mono": dict(
    titre="Comment choisir une imprimante laser noir et blanc",
    intro="Pour imprimer des documents, la laser monochrome est imbattable : <b>rapide, fiable, et un toner qui ne sèche jamais</b> même après des semaines sans imprimer.",
    criteres=[
        ("Imprimante seule ou multifonction", "Si vous scannez vos papiers, prenez un multifonction ; un chargeur de documents est utile au-delà de quelques pages."),
        ("Recto-verso", "Le recto-verso automatique économise du papier et du temps : il manque sur les modèles les moins chers."),
        ("Connectique", "Wi-Fi pour la maison, Ethernet pour le bureau partagé."),
        ("Coût du toner", "Comparez le rendement des toners (nombre de pages) : les toners haute capacité réduisent fortement le coût par page."),
    ],
    pieges=["Les toners de démarrage fournis avec l'imprimante, à moitié remplis.",
            "Les mises à jour qui bloquent les toners compatibles chez certaines marques.",
            "Acheter une laser couleur si vous n'imprimez que du texte."],
    budget=[("90 – 150 €", "Imprimante ou multifonction compacte."), ("150 – 280 €", "Recto-verso, chargeur, Ethernet.")],
),
"i-laser-couleur": dict(
    titre="Comment choisir une imprimante laser couleur",
    intro="La laser couleur imprime vite des documents nets et des graphiques éclatants, sans encre qui sèche. <b>Elle ne remplace pas une imprimante photo</b> : ses tirages restent granuleux.",
    criteres=[
        ("Volume", "Une laser couleur se justifie si vous imprimez régulièrement des documents en couleur ; sinon, un jet d'encre suffit."),
        ("Fonctions", "Multifonction avec chargeur si vous scannez ; imprimante seule si vous imprimez uniquement."),
        ("Toners", "Quatre toners à remplacer : comparez leur prix et leur rendement avant d'acheter."),
        ("Encombrement", "Les lasers couleur sont plus volumineuses : vérifiez la place disponible."),
    ],
    pieges=["Imprimer des photos sur une laser : le rendu déçoit.",
            "Les toners couleur de démarrage, vite épuisés.",
            "Les délais de livraison très longs de certains modèles professionnels."],
    budget=[("180 – 250 €", "Imprimante couleur compacte."), ("250 – 400 €", "Multifonction couleur de bureau.")],
),
"i-photo": dict(
    titre="Comment choisir une imprimante photo",
    intro="Tout dépend du format : <b>petites photos de poche</b> à partager, <b>tirages 10 × 15</b> de qualité labo, ou <b>grands formats</b> pour le photographe passionné.",
    criteres=[
        ("Technologie", "Zink (papier sans encre) pour des stickers amusants ; film instantané Instax pour le style rétro ; sublimation pour des 10 × 15 durables ; jet d'encre 6 encres pour la qualité et les grands formats."),
        ("Format", "Mini photos 5 × 7,6 cm, Instax mini ou Wide, 10 × 15, A4 ou A3+ : choisissez selon l'usage."),
        ("Coût par tirage", "Le prix de l'imprimante compte peu : regardez le prix par photo (papier et encre ou film)."),
        ("Connexion", "Bluetooth ou Wi-Fi avec une application sur smartphone pour les modèles nomades ; Wi-Fi et USB pour les modèles de bureau."),
    ],
    pieges=["Les imprimantes de poche pour des tirages « qualité labo » : elles en sont loin.",
            "Le coût du film instantané, élevé à chaque photo.",
            "Une grande imprimante photo pour quelques tirages par an : l'encre coûte cher si elle sèche."],
    budget=[("80 – 130 €", "Imprimantes de poche, instantanées ou 10 × 15."), ("400 – 600 €", "Imprimantes photo à réservoirs A4 et A3+.")],
),
"i-lowcost": dict(
    titre="Comment choisir une imprimante à moins de 150 €",
    intro="Pour imprimer un billet, une attestation ou quelques photos, une multifonction jet d'encre bon marché suffit. <b>Mais c'est le prix des cartouches qui fait la facture.</b>",
    criteres=[
        ("Volume", "Quelques pages par mois : une imprimante à cartouches convient. Au-delà, un réservoir d'encre sera vite rentable."),
        ("Recto-verso", "Le recto-verso automatique fait gagner du papier et du temps : il existe dès 70 €."),
        ("Abonnements d'encre", "Les offres d'abonnement des constructeurs peuvent réduire le coût, mais engagent : lisez les conditions."),
        ("Scanner et chargeur", "Un chargeur de documents est utile pour numériser plusieurs pages (dossiers administratifs)."),
    ],
    pieges=["L'imprimante à 40 € dont les cartouches coûtent aussi cher qu'elle.",
            "Les cartouches de démarrage, peu remplies.",
            "Laisser l'imprimante inutilisée des mois : les cartouches sèchent."],
    budget=[("40 – 70 €", "Multifonction basique."), ("70 – 150 €", "Recto-verso, écran, chargeur de documents.")],
),
}
