# -*- coding: utf-8 -*-
"""Fiches produits : « pour qui » / « à éviter si ».
Reformulation des points forts et points faibles relevés par la presse (catalog.py) — aucune donnée nouvelle.
Clé = identifiant du catalogue. Valeur = (pour qui, à éviter si)."""

PROFILES = {
    # ---------------------------------------------------------------- PC portables · Bureautique
    "zenbook-a14": ("Vous travaillez souvent hors de chez vous et voulez un PC de moins d'un kilo, qui tient plus d'une journée sans chargeur.",
                    "Vous utilisez des logiciels Windows exigeants ou pas encore adaptés aux puces ARM."),
    "mba13-m5": ("Vous voulez un ultraportable rapide et totalement silencieux, à garder plusieurs années.",
                 "Vous tenez à un écran OLED ou 120 Hz, ou vous voulez pouvoir ajouter de la mémoire plus tard."),
    "macbook-neo": ("Vous voulez entrer dans l'univers Mac au prix le plus bas, pour le web, les cours et la bureautique.",
                    "Vous ouvrez beaucoup d'applications à la fois : 8 Go de RAM et 256 Go sont vite justes."),
    "surface-pro-12": ("Vous cherchez une tablette Windows très légère et silencieuse, à utiliser autant au doigt qu'au clavier.",
                       "Vous ne voulez pas payer le clavier en plus, ou vous avez besoin de plus de deux ports USB-C."),
    "surface-laptop-13": ("Vous voulez un petit portable très bien fini, silencieux, au clavier confortable.",
                          "Vous attendez un écran OLED à ce prix, ou vous branchez beaucoup de périphériques."),
    "zenbook-a16": ("Vous voulez un grand écran OLED de 16 pouces sans le poids habituel : 1,2 kg et une grosse autonomie.",
                    "Vous travaillez face à une fenêtre (dalle brillante) ou vous avez besoin d'un pavé numérique."),
    "omnibook5-14": ("Vous faites surtout de la bureautique et voulez une très longue autonomie avec un écran OLED.",
                     "Vous comptez jouer ou monter des vidéos : la partie graphique est très juste."),
    "ideapad-slim3x": ("Vous voulez un 15 pouces endurant, qui ne chauffe pas et ne fait pas de bruit, à prix contenu.",
                       "La qualité d'écran compte pour vous, ou vous sortez de la bureautique."),
    "galaxy-book4-edge": ("Vous avez déjà un téléphone Galaxy et voulez un 15 pouces fin et endurant qui s'y connecte bien.",
                          "Vous dépendez de logiciels dont la compatibilité ARM n'est pas garantie."),
    "swift-air-14": ("Vous êtes étudiant ou très mobile et voulez un 14 pouces léger avec un écran antireflet fluide.",
                     "Vous travaillez souvent en extérieur (luminosité limitée) ou vous avez besoin de puissance."),
    # ---------------------------------------------------------------- PC portables · Création
    "mbp14-m5": ("Vous retouchez des photos ou montez des vidéos et voulez un écran calibré dès la sortie de la boîte, avec toute la connectique.",
                 "Vous voulez pouvoir faire évoluer la mémoire ou le stockage après l'achat."),
    "xps14": ("Vous voulez l'ultraportable Windows le plus soigné du moment : finition, écran, son et autonomie.",
              "Votre budget est limité, ou vous avez besoin d'autres ports que l'USB-C."),
    "proart-p16": ("Vous êtes créatif et voulez une station mobile : écran OLED tactile fidèle, carte RTX et lecteur de cartes SD.",
                   "Le prix est un critère, ou les reflets d'une dalle brillante vous gênent."),
    "proart-px13": ("Vous voulez le maximum de puissance dans un 13 pouces convertible, avec stylet.",
                    "Vous cherchez une grosse autonomie ou une machine silencieuse pendant les rendus."),
    "yoga-pro9": ("Vous voulez l'équivalent Windows du MacBook Pro : écran OLED très lumineux, carte NVIDIA, connectique complète.",
                  "Le bruit de ventilation en mode performance vous dérange."),
    "yoga-pro7": ("Vous voulez un 15 pouces multimédia bien équilibré, avec un très bel écran et 32 Go de RAM.",
                  "Vous préférez vous appuyer sur de nombreux tests : cette configuration en compte peu."),
    "zenbook-duo": ("Vous montez ou retouchez en déplacement et voulez deux écrans OLED sans emporter un moniteur.",
                    "Vous cherchez le portable le plus fin et le plus endurant possible."),
    "aero-x16": ("Vous voulez un 16 pouces fin avec carte RTX, pour jouer et monter en 1080p à prix contenu.",
                 "Vous faites de la retouche couleur exigeante : l'écran n'est pas fait pour cela."),
    "mba15-m5": ("Vous faites de la photo et du montage léger et voulez un grand écran dans un portable silencieux.",
                 "Vous montez de la vidéo lourde : il n'y a pas de carte graphique dédiée."),
    "zephyrus-g16": ("Vous voulez une machine fine capable de tout : vidéo, 3D et jeu, sur un écran OLED 240 Hz.",
                     "Votre budget est serré, ou vous travaillez longtemps loin d'une prise."),
    # ---------------------------------------------------------------- PC portables · Gaming
    "legion5": ("Vous voulez jouer sur un écran OLED 165 Hz sans exploser votre budget.",
                "Vous jouez dans une pièce très éclairée (écran réfléchissant) ou vous visez le très haut de gamme."),
    "omen-max-16": ("Vous voulez de très grosses performances en jeu sur un écran 240 Hz, pour un usage surtout sédentaire.",
                    "Vous comptez le transporter souvent : il est lourd et son autonomie est faible."),
    "helios-neo-16": ("Vous voulez jouer en QHD sur une dalle OLED, branché sur secteur.",
                      "Vous avez besoin d'autonomie : comptez 2 à 3 heures."),
    "loq15": ("Vous débutez dans le jeu sur PC portable et voulez une machine sérieuse et évolutive.",
              "La qualité de l'écran et du clavier compte beaucoup pour vous."),
    "katana15": ("Vous cherchez un maximum de puissance en jeu pour le prix, avec un clavier confortable.",
                 "Vous êtes sensible au bruit, ou exigeant sur l'écran."),
    "cyborg15": ("Vous voulez un PC gamer d'entrée de gamme de moins de 2 kg pour jouer en 1080p.",
                 "Vous attendez un écran lumineux et une finition soignée."),
    "crosshair16": ("Vous voulez jouer confortablement en haute définition sur un écran 240 Hz.",
                    "Vous voulez un châssis métal ou une bonne autonomie."),
    "strix-g16": ("Vous voulez une machine de jeu très complète, facile à ouvrir pour la faire évoluer.",
                  "Le bruit en charge vous gêne, ou vous attendez un châssis métal à ce prix."),
    "gigabyte-a16": ("Vous voulez un 16 pouces RTX à prix serré, plutôt silencieux et endurant pour un gamer.",
                     "Vous avez besoin de couleurs fidèles ou de plusieurs ports USB-C rapides."),
    "nitro-v16": ("Vous voulez un grand écran rapide et une RTX 5060 dans un châssis discret.",
                  "Vous cherchez une finition métal ou une bonne autonomie."),
    # ---------------------------------------------------------------- PC portables · Polyvalent
    "yoga-slim7": ("Vous voulez un seul PC pour tout faire, léger, endurant, avec un écran OLED bien calibré.",
                   "Vous comptez jouer régulièrement à des jeux récents."),
    "yoga-slim7x": ("Vous voulez un portable fin et endurant avec l'un des plus beaux écrans OLED de la catégorie.",
                    "Vous avez des logiciels à compatibilité ARM incertaine, ou un casque filaire."),
    "vivobook-s14": ("Vous voulez un écran OLED et une douzaine d'heures d'autonomie pour moins de 1 000 €.",
                     "Vous travaillez dans des lieux très lumineux, ou vous voulez jouer."),
    "zenbook-s14": ("Vous voulez un ultraportable premium très fin, silencieux et endurant.",
                    "Vous avez besoin de puissance graphique, ou vous voulez pouvoir ajouter de la RAM."),
    "zenbook-s16": ("Vous voulez un grand écran OLED 120 Hz dans un portable de 1,5 kg.",
                    "Vous faites tourner des tâches lourdes longtemps : il chauffe en charge."),
    "omnibook-x-flip14": ("Vous voulez un convertible compact, au clavier confortable et à l'écran OLED tactile.",
                          "Le son et l'autonomie sont prioritaires pour vous."),
    "yoga7-2in1": ("Vous voulez un convertible OLED pour travailler au clavier et regarder des films en mode tablette.",
                   "Vous l'utiliserez surtout en tablette tenue à la main : il est un peu lourd pour cela."),
    "ideapad-slim5-16": ("Vous cherchez un grand écran OLED pour la famille à moins de 1 000 €.",
                         "Vous voulez jouer : il n'a pas de carte graphique dédiée."),
    "swift16ai": ("Vous voulez un grand ultraportable frais, silencieux et endurant, avec un bel écran OLED.",
                  "Vous êtes gêné par les reflets ou par le prix de la configuration haut de gamme."),
    "lg-gram17": ("Vous voulez un écran de 17 pouces que vous pouvez emporter partout : moins de 1,4 kg.",
                  "Vous faites de la retouche photo : le calibrage de l'écran a été critiqué."),
    # ---------------------------------------------------------------- PC portables · Low-cost
    "aspire-go-15": ("Vous avez un petit budget et des besoins simples : web, cours, bureautique.",
                     "Vous regardez beaucoup de films ou de photos : l'écran est terne."),
    "ideapad-slim3": ("Vous cherchez un prix d'appel et vous savez choisir la bonne configuration (Ryzen 5 et vrai SSD).",
                      "Vous prendriez la version Athlon / 128 Go, trop limitée."),
    "ideapad1": ("Vous voulez le plus de mémoire et de stockage possible pour le prix : 16 Go et 512 Go.",
                 "La qualité de l'écran et de la finition compte pour vous."),
    "chromebook-315": ("Vous faites tout dans un navigateur et voulez un grand écran à très petit prix.",
                       "Vous avez besoin de logiciels Windows ou de beaucoup de stockage."),
    "chromebook-plus-514": ("Vous voulez un Chromebook solide et confortable, qui ne ralentit pas.",
                            "Vous travaillez souvent en extérieur ou loin d'une prise."),
    "chromebook-duet": ("Vous voulez une tablette légère avec clavier pour prendre des notes et regarder des vidéos.",
                        "Vous comptez travailler de longues heures dessus : l'écran est petit."),
    "vivobook-14": ("Vous voulez un PC Windows d'appoint au plus petit prix, pour le web et le traitement de texte.",
                    "Vous installez beaucoup de logiciels : 128 Go de stockage, c'est très peu."),
    "vivobook-go-14": ("Vous cherchez un petit portable d'appoint avec un écran Full HD.",
                       "Vous en ferez votre ordinateur principal : la puissance est très limitée."),
    "lenovo-v15": ("Vous voulez un 15 pouces avec pavé numérique pour travailler sur un bureau.",
                   "Vous travaillez en déplacement : l'autonomie est décevante."),
    "chromebook-cx14": ("Vous voulez un Chromebook 14 pouces Full HD bien équipé pour son prix.",
                        "Vous avez besoin d'applications hors du navigateur."),
    # ---------------------------------------------------------------- Ordinateurs de bureau · Bureautique
    "mac-mini-m6": ("Vous voulez un ordinateur de bureau minuscule, silencieux et très rapide.",
                    "Vous voulez pouvoir ajouter de la mémoire ou du stockage plus tard."),
    "ideacentre-mini": ("Vous voulez un mini-PC de grande marque pour la bureautique, avec Thunderbolt 4.",
                        "Vous avez besoin de puissance graphique ou de beaucoup de stockage."),
    "omnidesk-slim": ("Vous voulez une tour fine et peu chère pour le web, les mails et la bureautique.",
                      "Vous voulez la faire évoluer, ou vous prenez la version 8 Go pour un usage intensif."),
    "dell-slim": ("Vous voulez une tour silencieuse et économe, que vous pourrez faire évoluer.",
                  "Vous attendez des performances élevées ou une carte graphique."),
    "ideacentre-tower": ("Vous voulez une tour familiale avec de la place pour ajouter un disque ou une carte graphique.",
                         "Vous prévoyez une grosse carte graphique : l'alimentation est limitée."),
    "asus-v500": ("Vous voulez une petite tour soignée et silencieuse pour le travail quotidien.",
                  "Vous comptez la faire évoluer dans les années à venir."),
    "aspire-xc": ("Vous cherchez une tour compacte à prix serré, peu gourmande en énergie.",
                  "Vous n'avez ni clavier ni souris, ou vous prenez la version 8 Go pour un usage intensif."),
    "geekom-a5": ("Vous voulez un mini-PC quasi inaudible pour la bureautique, facile à ouvrir pour ajouter de la mémoire.",
                  "Vous voulez un processeur de dernière génération ou jouer."),
    "geekom-air12-lite": ("Vous avez un usage basique (web, bureautique, vidéo) et le plus petit budget possible.",
                          "Vous gardez beaucoup d'onglets et d'applications ouverts : 8 Go de RAM seulement."),
    "geekom-it12": ("Vous voulez un mini-PC Intel compact à la connectique très complète.",
                    "Vous cherchez le silence : le ventilateur s'entend presque toujours."),
    # ---------------------------------------------------------------- Ordinateurs de bureau · Création
    "mac-mini-m5pro": ("Vous faites de la photo ou du montage et voulez une station puissante qui tient dans la main.",
                       "Vous voulez pouvoir ajouter de la mémoire plus tard : les options sont chères et rien n'évolue."),
    "mac-studio-m5max": ("Vous avez besoin de performances de très haut niveau, en silence, avec tous les ports.",
                         "Vous voulez une machine modulable."),
    "geekom-a9max": ("Vous voulez un mini-PC très puissant, livré avec 32 Go de RAM et 2 To.",
                     "Votre travail repose sur la carte graphique : elle reste intégrée."),
    "geekom-it15": ("Vous voulez beaucoup de puissance processeur dans un boîtier de poche, avec deux ports USB4.",
                    "Vous voulez aussi jouer : la puce graphique n'est pas faite pour cela."),
    "geekom-gt1mega": ("Vous voulez un processeur haut de gamme et une connectique très complète pour moins de 900 €.",
                       "Vous êtes sensible au bruit quand la machine tourne à pleine puissance."),
    "hp-z2-mini": ("Vous faites de la 3D ou de l'IA en local et voulez une station professionnelle compacte.",
                   "Vous travaillez dans une pièce calme : elle peut devenir très bruyante."),
    "thinkstation-p3": ("Vous faites de la CAO ou du rendu 3D et manquez de place sur le bureau.",
                        "Le bruit des ventilateurs en charge vous dérange."),
    "minisforum-ai-x1-pro": ("Vous voulez un mini-PC haut de gamme calme, en métal, avec alimentation intégrée.",
                             "Vous avez besoin d'une carte graphique dédiée."),
    "minisforum-ms-s1-max": ("Vous faites tourner des modèles d'IA en local ou du calcul lourd et avez besoin de beaucoup de mémoire.",
                             "Vous voulez pouvoir ajouter de la mémoire après l'achat."),
    "gmktec-evo-x2": ("Vous voulez la puce graphique intégrée la plus rapide et beaucoup de mémoire pour l'IA locale.",
                      "Vous voulez une machine évolutive ou très sobre en énergie."),
    # ---------------------------------------------------------------- Ordinateurs de bureau · Gaming
    "omen35l": ("Vous voulez une tour gaming puissante, élégante et évolutive, prête à jouer.",
                "Vous ne supportez pas les logiciels préinstallés, ou votre budget est serré."),
    "omen16l": ("Vous voulez une petite tour élégante pour jouer en 1080p.",
                "Vous voulez la faire évoluer : le format compact limite les possibilités."),
    "loq-tower": ("Vous voulez une tour gaming abordable et sobre pour jouer en 1080p.",
                  "Vous prévoyez de changer la carte graphique plus tard."),
    "legion-tower-5": ("Vous voulez une tour très rapide pour son prix, en 1080p et 1440p, avec des composants standards.",
                       "Vous cherchez une machine discrète : la ventilation s'entend."),
    "orion-7000": ("Vous voulez une grande tour spectaculaire, puissante et bien pourvue en ports.",
                   "Vous manquez de place : elle est très lourde et encombrante."),
    "nitro-60": ("Vous voulez une tour sobre et compacte qui fait bien tourner les jeux.",
                 "Vous voulez un processeur récent ou une vraie marge d'évolution."),
    "nitro-50": ("Vous voulez la tour gaming la moins chère possible avec une RTX 5060.",
                 "Vous comptez la faire évoluer."),
    "rog-g700": ("Vous voulez une tour gaming polyvalente, rapide dans tous les usages.",
                 "Votre budget est serré, ou vous avez besoin de beaucoup de stockage."),
    "aorus-prime-5": ("Vous voulez des performances de premier plan dans une tour très silencieuse et bien montée.",
                      "Votre budget est limité."),
    "area-51": ("Vous voulez la puissance maximale, dans une tour que vous pourrez faire évoluer.",
                "Vous manquez de place ou de budget : elle est énorme et très chère."),
    # ---------------------------------------------------------------- Ordinateurs de bureau · Mini-PC
    "geekom-a8": ("Vous voulez un mini-PC puissant et bien fini, capable de faire tourner des jeux légers.",
                  "Vous avez besoin d'un second SSD interne."),
    "geekom-a5pro": ("Vous voulez un mini-PC sobre pour la bureautique, avec deux emplacements SSD.",
                     "Vous voulez ajouter de la RAM plus tard ou brancher des périphériques USB4."),
    "geekom-a6": ("Vous voulez un mini-PC bien construit avec USB4, à prix intéressant.",
                  "Vous cherchez le silence : la ventilation s'entend."),
    "geekom-a7": ("Vous voulez le mini-PC le mieux noté de la sélection : fin, bien fini, avec deux ports USB4.",
                  "Vous avez besoin d'un second SSD interne."),
    "geekom-it13": ("Vous voulez beaucoup de puissance dans un petit volume, avec lecteur de cartes.",
                    "Vous êtes sensible au bruit du ventilateur en charge."),
    "beelink-eq14": ("Vous voulez un mini-PC très silencieux pour le web, la bureautique ou un petit serveur à la maison.",
                     "Vous avez besoin de puissance."),
    "beelink-ser9pro": ("Vous voulez un mini-PC compact et silencieux, capable de jouer de temps en temps.",
                        "Vous visez les jeux récents les plus exigeants."),
    "nipogi-am06pro": ("Vous voulez un Ryzen à prix serré, avec double réseau et un accès facile aux composants.",
                       "Vous attendez un boîtier en métal et un SSD rapide."),
    "acemagic-k1": ("Vous voulez le plus de cœurs possible pour le prix, avec mémoire et stockage évolutifs.",
                    "Vous voulez du matériel récent."),
    "gmktec-k13": ("Vous voulez un mini-PC ultra-fin, discret et très sobre en énergie.",
                   "Vous voulez pouvoir ajouter de la RAM plus tard."),
    # ---------------------------------------------------------------- Ordinateurs de bureau · Tout-en-un
    "imac-m4": ("Vous voulez le tout-en-un le plus abouti : bel écran 4,5K, réactivité, design.",
                "Vous stockez beaucoup de fichiers (256 Go sur le modèle de base) ou travaillez face à une fenêtre."),
    "omnistudio-x32": ("Vous voulez un très grand écran 4K et un seul câble sur le bureau, sous Windows.",
                       "Vous attendez un écran plus rapide que 60 Hz."),
    "omnistudio-x27": ("Vous voulez un tout-en-un Windows soigné en 27 pouces, avec une bonne webcam.",
                       "Vous voulez pouvoir le faire évoluer, ou votre budget est limité."),
    "hp-omnistudio-27": ("Vous voulez un grand écran pour la famille et la bureautique, à budget contenu.",
                         "Vous utilisez plusieurs applications lourdes à la fois : 8 Go de RAM."),
    "yoga-aio-32": ("Vous voulez un tout-en-un Windows haut de gamme : écran 4K superbe, design et son soignés.",
                    "Votre budget est limité."),
    "ideacentre-aio-27": ("Vous voulez un grand écran économe pour un usage familial.",
                          "Vous faites beaucoup de visio ou travaillez sur des documents détaillés : webcam médiocre, Full HD sur 27 pouces."),
    "asus-v400": ("Vous voulez un tout-en-un fin et discret, bien doté en mémoire dans ses versions Core 7.",
                  "Vous attendez mieux que du Full HD, ou voulez vous appuyer sur de nombreux tests."),
    "aspire-c27": ("Vous voulez un tout-en-un 27 pouces à l'écran fluide et au pied réglable.",
                   "Vous n'avez ni clavier ni souris, ou vous prenez la version 8 Go pour un usage intensif."),
    "dell-24-aio": ("Vous voulez un tout-en-un abordable, bon en visio : son et webcam de qualité.",
                    "Vous voulez un grand écran ou des performances élevées."),
    "msi-modern-am273": ("Vous voulez un 27 pouces WQHD qui sert aussi d'écran à un autre appareil.",
                         "Vous préférez un modèle très testé par la presse."),
}
